import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import { formatInventoryPrice, normalizeCurrencyCode } from "@/app/lib/inventoryItemModel";

export interface PurchaseOrderPdfLine {
  name: string;
  code?: string;
  sku?: string;
  unit: string;
  orderQuantity: number;
  unitCost: number | null;
  lineTotal: number | null;
  note?: string;
}

export interface PurchaseOrderPdfDetails {
  title: string;
  supplierName: string;
  supplierEmail?: string;
  expectedDeliveryDate?: string;
  status: string;
  notes?: string;
  internalReference?: string;
}

export interface PurchaseOrderPdfBranding {
  businessName: string;
  contactEmail?: string;
  contactPhone?: string;
  contactWebsite?: string;
}

export interface ExportPurchaseOrderPdfOptions {
  details: PurchaseOrderPdfDetails;
  lines: PurchaseOrderPdfLine[];
  branding: PurchaseOrderPdfBranding;
  currencyCode?: string;
}

function formatDateForDisplay(date: Date) {
  return new Intl.DateTimeFormat("en", {
    dateStyle: "medium",
    timeStyle: "short",
  }).format(date);
}

function formatDateOnly(value?: string) {
  if (!value) return "Not set";
  const date = new Date(`${value}T00:00:00`);
  if (Number.isNaN(date.getTime())) return value;

  return new Intl.DateTimeFormat("en", {
    dateStyle: "medium",
  }).format(date);
}

function formatDateForFilename(date: Date) {
  const year = date.getFullYear();
  const month = String(date.getMonth() + 1).padStart(2, "0");
  const day = String(date.getDate()).padStart(2, "0");

  return `${year}-${month}-${day}`;
}

function slugifyFilename(value: string) {
  return (
    value
      .trim()
      .replace(/[^a-z0-9]+/gi, "-")
      .replace(/(^-|-$)/g, "") || "purchase-order"
  );
}

function formatMoney(value: number | null, currencyCode: string) {
  return value === null ? "Not set" : formatInventoryPrice(value, currencyCode) || "Not set";
}

function drawHeader({
  document,
  pageWidth,
  margin,
  businessName,
  contactLine,
  generatedAt,
  title,
}: {
  document: jsPDF;
  pageWidth: number;
  margin: number;
  businessName: string;
  contactLine: string;
  generatedAt: Date;
  title: string;
}) {
  document.setFillColor(15, 23, 42);
  document.rect(0, 0, pageWidth, 34, "F");

  document.setFont("helvetica", "bold");
  document.setFontSize(12);
  document.setTextColor(255, 255, 255);
  document.text(businessName, margin, 12);
  document.setFontSize(18);
  document.text("Purchase Order", margin, 23);

  if (contactLine) {
    document.setFont("helvetica", "normal");
    document.setFontSize(7.5);
    document.setTextColor(203, 213, 225);
    document.text(contactLine, margin, 30);
  }

  document.setFont("helvetica", "bold");
  document.setFontSize(8.5);
  document.setTextColor(226, 232, 240);
  document.text(title, pageWidth - margin, 13, { align: "right" });
  document.setFont("helvetica", "normal");
  document.setFontSize(7);
  document.text(`Generated ${formatDateForDisplay(generatedAt)}`, pageWidth - margin, 22, {
    align: "right",
  });
  document.text("Generated by SydIN", pageWidth - margin, 30, { align: "right" });
}

function drawFooter({
  document,
  pageWidth,
  pageHeight,
  margin,
  pageNumber,
  pageCount,
  generatedAt,
}: {
  document: jsPDF;
  pageWidth: number;
  pageHeight: number;
  margin: number;
  pageNumber: number;
  pageCount: number;
  generatedAt: Date;
}) {
  document.setDrawColor(226, 232, 240);
  document.line(margin, pageHeight - 12, pageWidth - margin, pageHeight - 12);
  document.setFont("helvetica", "normal");
  document.setFontSize(7.5);
  document.setTextColor(100, 116, 139);
  document.text("Generated by SydIN", margin, pageHeight - 7);
  document.text(
    `Page ${pageNumber} of ${pageCount} | ${formatDateForDisplay(generatedAt)}`,
    pageWidth - margin,
    pageHeight - 7,
    { align: "right" }
  );
}

export async function exportPurchaseOrderPdf({
  details,
  lines,
  branding,
  currencyCode,
}: ExportPurchaseOrderPdfOptions) {
  const generatedAt = new Date();
  const currency = normalizeCurrencyCode(currencyCode, "USD");
  const document = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const pageWidth = document.internal.pageSize.getWidth();
  const pageHeight = document.internal.pageSize.getHeight();
  const margin = 14;
  const businessName = branding.businessName.trim() || "SydIN Account";
  const contactLine = [
    branding.contactEmail,
    branding.contactPhone,
    branding.contactWebsite,
  ]
    .filter(Boolean)
    .join("  |  ");
  const orderedLines = lines.filter((line) => line.orderQuantity > 0);
  const subtotal = orderedLines.reduce((total, line) => total + Number(line.lineTotal || 0), 0);
  const orderedQuantity = orderedLines.reduce(
    (total, line) => total + Number(line.orderQuantity || 0),
    0
  );

  drawHeader({
    document,
    pageWidth,
    margin,
    businessName,
    contactLine,
    generatedAt,
    title: details.title || "Purchase Order",
  });

  document.setFont("helvetica", "bold");
  document.setFontSize(10);
  document.setTextColor(15, 23, 42);
  document.text("Supplier", margin, 47);
  document.text("Order Details", pageWidth / 2 + 4, 47);

  document.setFont("helvetica", "normal");
  document.setFontSize(8.5);
  document.setTextColor(51, 65, 85);
  document.text(
    [
      details.supplierName || "Supplier not set",
      details.supplierEmail ? `Email: ${details.supplierEmail}` : "",
    ].filter(Boolean),
    margin,
    54,
    { maxWidth: pageWidth / 2 - margin - 6 }
  );
  document.text(
    [
      `PO: ${details.title || "Untitled purchase order"}`,
      `Status: ${details.status}`,
      `Expected delivery: ${formatDateOnly(details.expectedDeliveryDate)}`,
      details.internalReference ? `Reference: ${details.internalReference}` : "",
    ].filter(Boolean),
    pageWidth / 2 + 4,
    54,
    { maxWidth: pageWidth / 2 - margin - 4 }
  );

  const summaryY = 79;
  const cards = [
    ["Lines", String(orderedLines.length)],
    ["Ordered quantity", String(orderedQuantity)],
    ["Estimated subtotal", formatMoney(subtotal, currency)],
  ];
  const cardWidth = (pageWidth - margin * 2 - 6) / 3;
  cards.forEach(([label, value], index) => {
    const x = margin + index * (cardWidth + 3);
    document.setFillColor(248, 250, 252);
    document.setDrawColor(226, 232, 240);
    document.roundedRect(x, summaryY, cardWidth, 16, 2.5, 2.5, "FD");
    document.setFont("helvetica", "bold");
    document.setFontSize(6.8);
    document.setTextColor(100, 116, 139);
    document.text(label.toUpperCase(), x + 3, summaryY + 5.2);
    document.setFontSize(10.2);
    document.setTextColor(15, 23, 42);
    document.text(value, x + 3, summaryY + 12.2, { maxWidth: cardWidth - 6 });
  });

  autoTable(document, {
    startY: 104,
    head: [["Item", "Code / SKU", "Unit", "Qty", "Unit cost", "Line total", "Notes"]],
    body: orderedLines.map((line) => [
      line.name,
      [line.code, line.sku ? `SKU ${line.sku}` : ""].filter(Boolean).join("\n") || "-",
      line.unit || "Unit",
      line.orderQuantity,
      formatMoney(line.unitCost, currency),
      formatMoney(line.lineTotal, currency),
      line.note || "",
    ]),
    margin: { left: margin, right: margin, top: 39, bottom: 18 },
    showHead: "everyPage",
    pageBreak: "auto",
    rowPageBreak: "avoid",
    styles: {
      font: "helvetica",
      fontSize: 7.4,
      cellPadding: 2.3,
      overflow: "linebreak",
      valign: "top",
      lineColor: [226, 232, 240],
      lineWidth: 0.12,
      textColor: [15, 23, 42],
    },
    headStyles: {
      fillColor: [15, 23, 42],
      textColor: [255, 255, 255],
      fontStyle: "bold",
      fontSize: 7.4,
    },
    alternateRowStyles: { fillColor: [248, 250, 252] },
    columnStyles: {
      0: { cellWidth: 43 },
      1: { cellWidth: 26 },
      2: { cellWidth: 21 },
      3: { cellWidth: 16, halign: "right" },
      4: { cellWidth: 25, halign: "right" },
      5: { cellWidth: 26, halign: "right" },
      6: { cellWidth: 25 },
    },
    willDrawPage: () => {
      const pageNumber = document.getCurrentPageInfo().pageNumber;
      if (pageNumber > 1) {
        drawHeader({
          document,
          pageWidth,
          margin,
          businessName,
          contactLine,
          generatedAt,
          title: details.title || "Purchase Order",
        });
      }
    },
  });

  const finalY =
    (document as jsPDF & { lastAutoTable?: { finalY: number } }).lastAutoTable
      ?.finalY || 104;
  let notesY = finalY + 8;

  if (details.notes?.trim()) {
    if (notesY > pageHeight - 42) {
      document.addPage();
      notesY = 42;
    }
    document.setFillColor(248, 250, 252);
    document.setDrawColor(226, 232, 240);
    document.roundedRect(margin, notesY, pageWidth - margin * 2, 24, 2.5, 2.5, "FD");
    document.setFont("helvetica", "bold");
    document.setFontSize(8.5);
    document.setTextColor(15, 23, 42);
    document.text("Notes", margin + 4, notesY + 7);
    document.setFont("helvetica", "normal");
    document.setFontSize(8);
    document.setTextColor(51, 65, 85);
    document.text(details.notes.trim(), margin + 4, notesY + 14, {
      maxWidth: pageWidth - margin * 2 - 8,
    });
  }

  const pageCount = document.getNumberOfPages();
  for (let pageNumber = 1; pageNumber <= pageCount; pageNumber += 1) {
    document.setPage(pageNumber);
    drawFooter({
      document,
      pageWidth,
      pageHeight,
      margin,
      pageNumber,
      pageCount,
      generatedAt,
    });
  }

  const filename = `${slugifyFilename(
    businessName
  )}-${slugifyFilename(details.title || "purchase-order")}-${formatDateForFilename(
    generatedAt
  )}.pdf`;

  document.save(filename);
  return filename;
}
