-- SydIN Phase 10b: Asset Tracking (Scanner Workspace Stage 3)
-- Run manually in the Supabase SQL editor after reviewing.
--
-- Implements per-unit asset tracking: inventory_assets (one row per physical unit)
-- + append-only asset_events log, quantity derived by trigger, enabled per item
-- via inventory.is_asset_tracked flag. Free-text assignee with autocomplete.
-- See decision: https://github.com/FlowerSystem-lb/sydin/docs/SYDIN_DECISION_LOG.md

begin;

-- Per-unit asset tracking: each physical asset gets its own row
create table if not exists public.inventory_assets (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  inventory_item_id bigint not null references public.inventory(id) on delete cascade,
  public_id text not null unique,
  status text not null default 'in_stock',
  condition text null default 'good',
  assigned_to_name text null,
  serial_number text null,
  notes text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint inventory_assets_status_valid check (
    status in ('in_stock', 'in_use', 'in_repair', 'retired', 'lost')
  ),
  constraint inventory_assets_condition_valid check (
    condition is null
    or condition in ('good', 'fair', 'poor', 'damaged', 'unknown')
  ),
  constraint inventory_assets_public_id_not_blank check (
    btrim(public_id) <> ''
  ),
  constraint inventory_assets_assigned_to_not_blank check (
    assigned_to_name is null or btrim(assigned_to_name) <> ''
  ),
  constraint inventory_assets_serial_not_blank check (
    serial_number is null or btrim(serial_number) <> ''
  )
);

-- Append-only event log for asset status/condition/assignment changes
create table if not exists public.asset_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  inventory_asset_id bigint not null references public.inventory_assets(id) on delete cascade,
  event_type text not null,
  old_status text null,
  new_status text null,
  old_condition text null,
  new_condition text null,
  old_assigned_to text null,
  new_assigned_to text null,
  notes text null,
  recorded_by text null,
  created_at timestamptz not null default now(),
  constraint asset_events_type_valid check (
    event_type in (
      'created',
      'status_changed',
      'condition_changed',
      'assigned',
      'unassigned',
      'note_added',
      'retired'
    )
  )
);

-- Indexes for common queries
create index if not exists inventory_assets_user_item_idx
  on public.inventory_assets(user_id, inventory_item_id);

create index if not exists inventory_assets_status_idx
  on public.inventory_assets(status);

create index if not exists inventory_assets_assigned_to_idx
  on public.inventory_assets(assigned_to_name) where assigned_to_name is not null;

create index if not exists asset_events_asset_idx
  on public.asset_events(inventory_asset_id, created_at desc);

create index if not exists asset_events_user_created_idx
  on public.asset_events(user_id, created_at desc);

-- RLS: Users can only see/modify their own assets
alter table public.inventory_assets enable row level security;
alter table public.asset_events enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'inventory_assets'
      and policyname = 'inventory_assets_user_isolation'
  ) then
    create policy inventory_assets_user_isolation
      on public.inventory_assets
      for all
      using (auth.uid() = user_id)
      with check (auth.uid() = user_id);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'asset_events'
      and policyname = 'asset_events_user_isolation'
  ) then
    create policy asset_events_user_isolation
      on public.asset_events
      for all
      using (auth.uid() = user_id)
      with check (auth.uid() = user_id);
  end if;
end $$;

-- Add is_asset_tracked flag to inventory if not present
alter table public.inventory
  add column if not exists is_asset_tracked boolean not null default false;

-- Trigger to derive quantity from active asset count when asset tracking is enabled
create or replace function public.sync_asset_tracked_quantity()
returns trigger as $$
declare
  active_count bigint;
begin
  if new.is_asset_tracked then
    -- Count non-retired assets for this item
    select count(*)
      into active_count
      from public.inventory_assets
      where inventory_item_id = new.id
        and status <> 'retired'
        and status <> 'lost';

    new.quantity := coalesce(active_count, 0);
  end if;
  return new;
end;
$$ language plpgsql;

-- Drop existing trigger if present to avoid conflicts
do $$
begin
  drop trigger if exists sync_asset_quantity_on_item_update on public.inventory;
exception when others then
  null;
end $$;

-- Create the trigger to keep derived quantity in sync
create trigger sync_asset_quantity_on_item_update
  before update on public.inventory
  for each row
  execute function public.sync_asset_tracked_quantity();

-- Trigger to update quantity when asset status changes
create or replace function public.update_quantity_on_asset_event()
returns trigger as $$
declare
  item_is_tracked boolean;
  new_qty bigint;
begin
  select is_asset_tracked
    into item_is_tracked
    from public.inventory
    where id = new.inventory_item_id;

  if item_is_tracked then
    select count(*)
      into new_qty
      from public.inventory_assets
      where inventory_item_id = new.inventory_item_id
        and status <> 'retired'
        and status <> 'lost';

    update public.inventory
      set quantity = coalesce(new_qty, 0), updated_at = now()
      where id = new.inventory_item_id;
  end if;
  return new;
end;
$$ language plpgsql;

-- Drop and recreate trigger to ensure it exists
do $$
begin
  drop trigger if exists update_qty_on_asset_status_change on public.inventory_assets;
exception when others then
  null;
end $$;

create trigger update_qty_on_asset_status_change
  after update on public.inventory_assets
  for each row
  when (old.status is distinct from new.status or old.status is distinct from new.status)
  execute function public.update_quantity_on_asset_event();

-- RPC to record an asset event (single writer pattern)
create or replace function public.record_asset_event(
  asset_id bigint,
  event_type_arg text,
  new_status_arg text default null,
  new_condition_arg text default null,
  new_assigned_to_arg text default null,
  event_notes text default null,
  recorded_by_name text default null
) returns json as $$
declare
  user_id_var uuid;
  item_id bigint;
  old_status text;
  old_condition text;
  old_assigned_to text;
begin
  user_id_var := auth.uid();
  if user_id_var is null then
    raise exception 'Not authenticated';
  end if;

  -- Fetch asset, check ownership
  select inventory_item_id, status, condition, assigned_to_name
    into item_id, old_status, old_condition, old_assigned_to
    from public.inventory_assets
    where id = asset_id and user_id = user_id_var
    for update;

  if item_id is null then
    raise exception 'Asset not found or access denied';
  end if;

  -- Validate event type and required fields
  case event_type_arg
    when 'status_changed' then
      if new_status_arg is null then
        raise exception 'status_changed event requires new_status_arg';
      end if;
    when 'condition_changed' then
      if new_condition_arg is null then
        raise exception 'condition_changed event requires new_condition_arg';
      end if;
    when 'assigned' then
      if new_assigned_to_arg is null then
        raise exception 'assigned event requires new_assigned_to_arg';
      end if;
  end case;

  -- Record the event
  insert into public.asset_events (
    user_id,
    inventory_asset_id,
    event_type,
    old_status,
    new_status,
    old_condition,
    new_condition,
    old_assigned_to,
    new_assigned_to,
    notes,
    recorded_by
  ) values (
    user_id_var,
    asset_id,
    event_type_arg,
    old_status,
    coalesce(new_status_arg, old_status),
    old_condition,
    coalesce(new_condition_arg, old_condition),
    old_assigned_to,
    coalesce(new_assigned_to_arg, old_assigned_to),
    coalesce(btrim(event_notes), null),
    coalesce(btrim(recorded_by_name), null)
  );

  -- Apply the change to the asset
  update public.inventory_assets
    set
      status = coalesce(new_status_arg, status),
      condition = coalesce(new_condition_arg, condition),
      assigned_to_name = coalesce(new_assigned_to_arg, assigned_to_name),
      updated_at = now()
    where id = asset_id;

  return json_build_object(
    'success', true,
    'asset_id', asset_id,
    'event_type', event_type_arg,
    'new_status', coalesce(new_status_arg, old_status),
    'new_condition', coalesce(new_condition_arg, old_condition),
    'new_assigned_to', coalesce(new_assigned_to_arg, old_assigned_to)
  );
end;
$$ language plpgsql security definer;

grant execute on function public.record_asset_event(bigint, text, text, text, text, text, text)
  to authenticated;

-- Helper RPC to get distinct assignee names for autocomplete
create or replace function public.get_asset_assignee_suggestions(search_term text default '')
returns table(name text, count bigint) as $$
begin
  return query
    select
      assigned_to_name,
      count(*)::bigint
    from public.inventory_assets
    where user_id = auth.uid()
      and assigned_to_name is not null
      and (search_term = '' or assigned_to_name ilike '%' || search_term || '%')
    group by assigned_to_name
    order by count desc, assigned_to_name asc
    limit 50;
end;
$$ language plpgsql security definer;

grant execute on function public.get_asset_assignee_suggestions(text)
  to authenticated;

commit;
