-- SydIN Phase 7: Pick Lists and Order Preparation
-- Run manually in the Supabase SQL editor after reviewing.
--
-- The repository confirms the application-facing stock_movements columns used
-- below, but the original stock_movements table/function SQL is not tracked.

begin;

create table if not exists public.pick_lists (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  customer_name text null,
  due_date date null,
  status text not null default 'draft',
  notes text null,
  completion_stock_action text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  completed_at timestamptz null,
  cancelled_at timestamptz null,
  constraint pick_lists_title_not_blank check (btrim(title) <> ''),
  constraint pick_lists_status_valid check (
    status in ('draft', 'preparing', 'completed', 'cancelled')
  ),
  constraint pick_lists_completion_stock_action_valid check (
    completion_stock_action is null
    or completion_stock_action in ('deducted', 'skipped')
  ),
  constraint pick_lists_terminal_state_consistent check (
    (
      status in ('draft', 'preparing')
      and completion_stock_action is null
      and completed_at is null
      and cancelled_at is null
    )
    or (
      status = 'completed'
      and completion_stock_action in ('deducted', 'skipped')
      and completed_at is not null
      and cancelled_at is null
    )
    or (
      status = 'cancelled'
      and completion_stock_action is null
      and completed_at is null
      and cancelled_at is not null
    )
  )
);

create table if not exists public.pick_list_items (
  id bigint generated by default as identity primary key,
  pick_list_id bigint not null references public.pick_lists(id) on delete cascade,
  inventory_item_id bigint null references public.inventory(id) on delete set null,
  required_quantity integer not null,
  prepared_quantity integer not null default 0,
  notes text null,
  item_name_snapshot text not null,
  item_code_snapshot text null,
  sku_snapshot text null,
  unit_label_snapshot text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint pick_list_items_required_quantity_positive check (
    required_quantity > 0
  ),
  constraint pick_list_items_prepared_quantity_valid check (
    prepared_quantity >= 0
    and prepared_quantity <= required_quantity
  ),
  constraint pick_list_items_name_snapshot_not_blank check (
    btrim(item_name_snapshot) <> ''
  )
);

create index if not exists pick_lists_user_status_created_idx
  on public.pick_lists(user_id, status, created_at desc);

create index if not exists pick_lists_user_due_date_idx
  on public.pick_lists(user_id, due_date);

create index if not exists pick_list_items_pick_list_id_idx
  on public.pick_list_items(pick_list_id);

create index if not exists pick_list_items_inventory_item_id_idx
  on public.pick_list_items(inventory_item_id);

create unique index if not exists pick_list_items_list_inventory_uidx
  on public.pick_list_items(pick_list_id, inventory_item_id)
  where inventory_item_id is not null;

alter table public.stock_movements
  add column if not exists pick_list_id bigint null;

alter table public.stock_movements
  add column if not exists pick_list_item_id bigint null;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'stock_movements_pick_list_id_fkey'
      and conrelid = 'public.stock_movements'::regclass
  ) then
    alter table public.stock_movements
      add constraint stock_movements_pick_list_id_fkey
      foreign key (pick_list_id)
      references public.pick_lists(id)
      on delete set null;
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'stock_movements_pick_list_item_id_fkey'
      and conrelid = 'public.stock_movements'::regclass
  ) then
    alter table public.stock_movements
      add constraint stock_movements_pick_list_item_id_fkey
      foreign key (pick_list_item_id)
      references public.pick_list_items(id)
      on delete set null;
  end if;
end
$$;

create index if not exists stock_movements_pick_list_id_idx
  on public.stock_movements(pick_list_id);

create unique index if not exists stock_movements_pick_list_item_uidx
  on public.stock_movements(pick_list_item_id)
  where pick_list_item_id is not null;

create or replace function public.enforce_pick_list_active_limit()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  effective_plan text := 'free';
  active_limit integer;
  active_count integer;
begin
  if auth.uid() is null or new.user_id <> auth.uid() then
    raise exception 'Pick list must belong to the authenticated user.'
      using errcode = '42501';
  end if;

  select case
    when lower(coalesce(us.status, '')) = 'active'
      then lower(coalesce(us.plan, 'free'))
    else 'free'
  end
  into effective_plan
  from public.user_subscriptions us
  where us.user_id = new.user_id;

  effective_plan := coalesce(effective_plan, 'free');

  if effective_plan = 'pro' then
    return new;
  end if;

  active_limit := case
    when effective_plan = 'standard' then 50
    else 3
  end;

  select count(*)
  into active_count
  from public.pick_lists pl
  where pl.user_id = new.user_id
    and pl.status in ('draft', 'preparing');

  if active_count >= active_limit then
    raise exception 'Active Pick List limit reached for the current plan.'
      using errcode = 'P0001';
  end if;

  return new;
end;
$$;

drop trigger if exists pick_lists_enforce_active_limit
  on public.pick_lists;
create trigger pick_lists_enforce_active_limit
before insert on public.pick_lists
for each row
execute function public.enforce_pick_list_active_limit();

create or replace function public.normalize_pick_list()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.title = btrim(new.title);
  new.customer_name = nullif(btrim(new.customer_name), '');
  new.notes = nullif(btrim(new.notes), '');

  if tg_op = 'INSERT' then
    if new.status <> 'draft' then
      raise exception 'New pick lists must start as draft.'
        using errcode = '23514';
    end if;

    new.completion_stock_action = null;
    new.completed_at = null;
    new.cancelled_at = null;
    return new;
  end if;

  if new.user_id is distinct from old.user_id then
    raise exception 'Pick list ownership cannot be changed.'
      using errcode = '23514';
  end if;

  if old.status in ('completed', 'cancelled') then
    raise exception 'Completed or cancelled pick lists cannot be changed.'
      using errcode = '55000';
  end if;

  if old.status = 'draft'
     and new.status not in ('draft', 'preparing', 'cancelled') then
    raise exception 'Invalid pick list status transition.'
      using errcode = '23514';
  end if;

  if old.status = 'preparing'
     and new.status not in ('preparing', 'completed', 'cancelled') then
    raise exception 'Invalid pick list status transition.'
      using errcode = '23514';
  end if;

  if new.status = 'completed'
     and coalesce(
       current_setting('sydin.complete_pick_list', true),
       ''
     ) <> 'on' then
    raise exception 'Pick lists must be completed through complete_pick_list.'
      using errcode = '42501';
  end if;

  if new.status = 'cancelled' then
    new.cancelled_at = coalesce(new.cancelled_at, now());
    new.completed_at = null;
    new.completion_stock_action = null;
  elsif new.status in ('draft', 'preparing') then
    new.cancelled_at = null;
    new.completed_at = null;
    new.completion_stock_action = null;
  end if;

  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists pick_lists_normalize on public.pick_lists;
create trigger pick_lists_normalize
before insert or update on public.pick_lists
for each row
execute function public.normalize_pick_list();

create or replace function public.normalize_and_validate_pick_list_item()
returns trigger
language plpgsql
set search_path = public
as $$
declare
  owner_id uuid;
  parent_status text;
begin
  new.item_name_snapshot = btrim(new.item_name_snapshot);
  new.item_code_snapshot = nullif(btrim(new.item_code_snapshot), '');
  new.sku_snapshot = nullif(btrim(new.sku_snapshot), '');
  new.unit_label_snapshot = nullif(btrim(new.unit_label_snapshot), '');
  new.notes = nullif(btrim(new.notes), '');

  select pl.user_id, pl.status
  into owner_id, parent_status
  from public.pick_lists pl
  where pl.id = new.pick_list_id;

  if owner_id is null then
    raise exception 'Pick list not found.'
      using errcode = '23503';
  end if;

  if auth.uid() is null or owner_id <> auth.uid() then
    raise exception 'Pick list item must belong to the authenticated user.'
      using errcode = '42501';
  end if;

  if parent_status not in ('draft', 'preparing') then
    if tg_op = 'UPDATE'
       and old.inventory_item_id is not null
       and new.inventory_item_id is null
       and new.pick_list_id = old.pick_list_id
       and new.required_quantity = old.required_quantity
       and new.prepared_quantity = old.prepared_quantity
       and new.notes is not distinct from old.notes
       and new.item_name_snapshot = old.item_name_snapshot
       and new.item_code_snapshot is not distinct from old.item_code_snapshot
       and new.sku_snapshot is not distinct from old.sku_snapshot
       and new.unit_label_snapshot is not distinct from old.unit_label_snapshot then
      new.updated_at = old.updated_at;
      return new;
    end if;

    raise exception 'Completed or cancelled pick list items cannot be changed.'
      using errcode = '55000';
  end if;

  if new.inventory_item_id is not null
     and not exists (
       select 1
       from public.inventory i
       where i.id = new.inventory_item_id
         and i.user_id = owner_id
     ) then
    raise exception 'Inventory item must belong to the pick list owner.'
      using errcode = '23514';
  end if;

  if tg_op = 'UPDATE' then
    if new.pick_list_id is distinct from old.pick_list_id then
      raise exception 'Pick list items cannot be moved between lists.'
        using errcode = '23514';
    end if;

    new.updated_at = now();
  end if;

  return new;
end;
$$;

drop trigger if exists pick_list_items_normalize_validate
  on public.pick_list_items;
create trigger pick_list_items_normalize_validate
before insert or update on public.pick_list_items
for each row
execute function public.normalize_and_validate_pick_list_item();

create or replace function public.guard_pick_list_item_delete()
returns trigger
language plpgsql
set search_path = public
as $$
declare
  owner_id uuid;
  parent_status text;
begin
  if pg_trigger_depth() > 1 then
    return old;
  end if;

  select pl.user_id, pl.status
  into owner_id, parent_status
  from public.pick_lists pl
  where pl.id = old.pick_list_id;

  if auth.uid() is null or owner_id <> auth.uid() then
    raise exception 'Pick list item must belong to the authenticated user.'
      using errcode = '42501';
  end if;

  if parent_status not in ('draft', 'preparing') then
    raise exception 'Completed or cancelled pick list items cannot be removed.'
      using errcode = '55000';
  end if;

  return old;
end;
$$;

drop trigger if exists pick_list_items_guard_delete
  on public.pick_list_items;
create trigger pick_list_items_guard_delete
before delete on public.pick_list_items
for each row
execute function public.guard_pick_list_item_delete();

create or replace function public.prevent_active_pick_list_inventory_delete()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if exists (
    select 1
    from public.pick_list_items pli
    join public.pick_lists pl on pl.id = pli.pick_list_id
    where pli.inventory_item_id = old.id
      and pl.status in ('draft', 'preparing')
  ) then
    raise exception
      'This inventory item belongs to an active pick list. Remove it from the pick list before deleting it.'
      using errcode = '55000';
  end if;

  return old;
end;
$$;

drop trigger if exists inventory_prevent_active_pick_list_delete
  on public.inventory;
create trigger inventory_prevent_active_pick_list_delete
before delete on public.inventory
for each row
execute function public.prevent_active_pick_list_inventory_delete();

create or replace function public.complete_pick_list(
  p_pick_list_id bigint,
  p_deduct_stock boolean
)
returns public.pick_lists
language plpgsql
security definer
set search_path = public
as $$
declare
  authenticated_user_id uuid;
  completed_list public.pick_lists%rowtype;
  line_count integer;
  line_record record;
  quantity_before integer;
begin
  authenticated_user_id := auth.uid();

  if authenticated_user_id is null then
    raise exception 'Authentication is required.'
      using errcode = '42501';
  end if;

  select *
  into completed_list
  from public.pick_lists
  where id = p_pick_list_id
  for update;

  if not found or completed_list.user_id <> authenticated_user_id then
    raise exception 'Pick list not found.'
      using errcode = '42501';
  end if;

  if completed_list.status <> 'preparing' then
    raise exception 'Only preparing pick lists can be completed.'
      using errcode = '55000';
  end if;

  if p_deduct_stock is null then
    raise exception 'Choose whether completion should deduct stock.'
      using errcode = '23514';
  end if;

  perform pli.id
  from public.pick_list_items pli
  where pli.pick_list_id = p_pick_list_id
  order by pli.id
  for update;

  select count(*)
  into line_count
  from public.pick_list_items
  where pick_list_id = p_pick_list_id;

  if line_count = 0 then
    raise exception 'Add at least one item before completing this pick list.'
      using errcode = '23514';
  end if;

  if exists (
    select 1
    from public.pick_list_items
    where pick_list_id = p_pick_list_id
      and prepared_quantity <> required_quantity
  ) then
    raise exception 'Every item must be fully prepared before completion.'
      using errcode = '23514';
  end if;

  if p_deduct_stock then
    if exists (
      select 1
      from public.pick_list_items
      where pick_list_id = p_pick_list_id
        and inventory_item_id is null
    ) then
      raise exception
        'A linked inventory item is no longer available. Complete without deduction or remove the line before completion.'
        using errcode = '23514';
    end if;

    perform i.id
    from public.inventory i
    join public.pick_list_items pli
      on pli.inventory_item_id = i.id
    where pli.pick_list_id = p_pick_list_id
    order by i.id
    for update of i;

    for line_record in
      select
        pli.id as pick_list_item_id,
        pli.inventory_item_id,
        pli.required_quantity,
        pli.item_name_snapshot,
        i.user_id as inventory_user_id,
        i.quantity as inventory_quantity
      from public.pick_list_items pli
      join public.inventory i on i.id = pli.inventory_item_id
      where pli.pick_list_id = p_pick_list_id
      order by i.id
    loop
      if line_record.inventory_user_id <> authenticated_user_id then
        raise exception 'Inventory item ownership does not match the pick list.'
          using errcode = '42501';
      end if;

      if line_record.inventory_quantity < line_record.required_quantity then
        raise exception 'Insufficient stock for %.', line_record.item_name_snapshot
          using errcode = '23514';
      end if;

      if exists (
        select 1
        from public.stock_movements sm
        where sm.pick_list_item_id = line_record.pick_list_item_id
      ) then
        raise exception 'Stock has already been deducted for this pick list item.'
          using errcode = '23505';
      end if;

      quantity_before := line_record.inventory_quantity;

      update public.inventory
      set quantity = quantity_before - line_record.required_quantity
      where id = line_record.inventory_item_id
        and user_id = authenticated_user_id;

      insert into public.stock_movements (
        user_id,
        item_id,
        movement_type,
        quantity_delta,
        quantity_before,
        quantity_after,
        notes,
        pick_list_id,
        pick_list_item_id
      )
      values (
        authenticated_user_id,
        line_record.inventory_item_id,
        'stock_out',
        -line_record.required_quantity,
        quantity_before,
        quantity_before - line_record.required_quantity,
        'Pick list #' || p_pick_list_id || ': ' || completed_list.title,
        p_pick_list_id,
        line_record.pick_list_item_id
      );
    end loop;
  end if;

  perform set_config('sydin.complete_pick_list', 'on', true);

  update public.pick_lists
  set
    status = 'completed',
    completion_stock_action = case
      when p_deduct_stock then 'deducted'
      else 'skipped'
    end,
    completed_at = now(),
    cancelled_at = null
  where id = p_pick_list_id
  returning * into completed_list;

  return completed_list;
end;
$$;

alter table public.pick_lists enable row level security;
alter table public.pick_list_items enable row level security;

drop policy if exists "Users can view own pick lists"
  on public.pick_lists;
create policy "Users can view own pick lists"
on public.pick_lists
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "Users can create own pick lists"
  on public.pick_lists;
create policy "Users can create own pick lists"
on public.pick_lists
for insert
to authenticated
with check (
  auth.uid() = user_id
  and status = 'draft'
);

drop policy if exists "Users can update active own pick lists"
  on public.pick_lists;
create policy "Users can update active own pick lists"
on public.pick_lists
for update
to authenticated
using (
  auth.uid() = user_id
  and status in ('draft', 'preparing')
)
with check (auth.uid() = user_id);

drop policy if exists "Users can delete active own pick lists"
  on public.pick_lists;
create policy "Users can delete active own pick lists"
on public.pick_lists
for delete
to authenticated
using (
  auth.uid() = user_id
  and status in ('draft', 'preparing')
);

drop policy if exists "Users can view own pick list items"
  on public.pick_list_items;
create policy "Users can view own pick list items"
on public.pick_list_items
for select
to authenticated
using (
  exists (
    select 1
    from public.pick_lists pl
    where pl.id = pick_list_id
      and pl.user_id = auth.uid()
  )
);

drop policy if exists "Users can create own active pick list items"
  on public.pick_list_items;
create policy "Users can create own active pick list items"
on public.pick_list_items
for insert
to authenticated
with check (
  exists (
    select 1
    from public.pick_lists pl
    where pl.id = pick_list_id
      and pl.user_id = auth.uid()
      and pl.status in ('draft', 'preparing')
  )
  and (
    inventory_item_id is null
    or exists (
      select 1
      from public.inventory i
      where i.id = inventory_item_id
        and i.user_id = auth.uid()
    )
  )
);

drop policy if exists "Users can update own active pick list items"
  on public.pick_list_items;
create policy "Users can update own active pick list items"
on public.pick_list_items
for update
to authenticated
using (
  exists (
    select 1
    from public.pick_lists pl
    where pl.id = pick_list_id
      and pl.user_id = auth.uid()
      and pl.status in ('draft', 'preparing')
  )
)
with check (
  exists (
    select 1
    from public.pick_lists pl
    where pl.id = pick_list_id
      and pl.user_id = auth.uid()
      and pl.status in ('draft', 'preparing')
  )
  and (
    inventory_item_id is null
    or exists (
      select 1
      from public.inventory i
      where i.id = inventory_item_id
        and i.user_id = auth.uid()
    )
  )
);

drop policy if exists "Users can delete own active pick list items"
  on public.pick_list_items;
create policy "Users can delete own active pick list items"
on public.pick_list_items
for delete
to authenticated
using (
  exists (
    select 1
    from public.pick_lists pl
    where pl.id = pick_list_id
      and pl.user_id = auth.uid()
      and pl.status in ('draft', 'preparing')
  )
);

revoke all on table public.pick_lists from anon;
revoke all on table public.pick_list_items from anon;
revoke all on sequence public.pick_lists_id_seq from anon;
revoke all on sequence public.pick_list_items_id_seq from anon;
revoke all on function public.complete_pick_list(bigint, boolean) from public;
revoke all on function public.complete_pick_list(bigint, boolean) from anon;
revoke all on function public.enforce_pick_list_active_limit() from public;
revoke all on function public.enforce_pick_list_active_limit() from anon;
revoke all on function public.enforce_pick_list_active_limit() from authenticated;

grant select, insert, update, delete
  on table public.pick_lists to authenticated;
grant select, insert, update, delete
  on table public.pick_list_items to authenticated;
grant usage, select
  on sequence public.pick_lists_id_seq to authenticated;
grant usage, select
  on sequence public.pick_list_items_id_seq to authenticated;
grant execute
  on function public.complete_pick_list(bigint, boolean) to authenticated;

notify pgrst, 'reload schema';

commit;
