-- SydIN Phase 6A: Professional Categories System
-- Run manually in the Supabase SQL editor after reviewing.

begin;

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  description text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint categories_name_not_blank check (btrim(name) <> '')
);

alter table public.inventory
  add column if not exists category_id bigint null;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'inventory_category_id_fkey'
      and conrelid = 'public.inventory'::regclass
  ) then
    alter table public.inventory
      add constraint inventory_category_id_fkey
      foreign key (category_id)
      references public.categories(id)
      on delete set null;
  end if;
end
$$;

create index if not exists categories_user_id_idx
  on public.categories(user_id);

create unique index if not exists categories_user_name_ci_uidx
  on public.categories(user_id, lower(btrim(name)));

create index if not exists inventory_user_category_idx
  on public.inventory(user_id, category_id);

create or replace function public.normalize_category_fields()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.name = btrim(new.name);
  new.description = nullif(btrim(new.description), '');

  if tg_op = 'UPDATE' then
    new.updated_at = now();
  end if;

  return new;
end;
$$;

drop trigger if exists categories_set_updated_at on public.categories;
drop trigger if exists categories_normalize_fields on public.categories;
create trigger categories_normalize_fields
before insert or update on public.categories
for each row
execute function public.normalize_category_fields();

create or replace function public.validate_inventory_category_owner()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if new.category_id is null then
    return new;
  end if;

  if not exists (
    select 1
    from public.categories c
    where c.id = new.category_id
      and c.user_id = new.user_id
  ) then
    raise exception 'Inventory category must belong to the same user.'
      using errcode = '23514';
  end if;

  return new;
end;
$$;

drop trigger if exists inventory_validate_category_owner on public.inventory;
create trigger inventory_validate_category_owner
before insert or update of category_id, user_id on public.inventory
for each row
execute function public.validate_inventory_category_owner();

create or replace function public.sync_category_name_to_inventory()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.name is distinct from old.name then
    update public.inventory
    set category = new.name
    where category_id = new.id
      and user_id = new.user_id;
  end if;

  return new;
end;
$$;

drop trigger if exists categories_sync_name_to_inventory on public.categories;
create trigger categories_sync_name_to_inventory
after update of name on public.categories
for each row
execute function public.sync_category_name_to_inventory();

create or replace function public.clear_deleted_category_from_inventory()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.inventory
  set category_id = null,
      category = null
  where category_id = old.id
    and user_id = old.user_id;

  return old;
end;
$$;

drop trigger if exists categories_clear_inventory_on_delete on public.categories;
create trigger categories_clear_inventory_on_delete
before delete on public.categories
for each row
execute function public.clear_deleted_category_from_inventory();

-- Normalize legacy values before backfill.
update public.inventory
set category = nullif(btrim(category), '')
where category is distinct from nullif(btrim(category), '');

-- Preserve display casing from the earliest inventory row in each
-- case-insensitive category group.
with ranked_legacy_categories as (
  select
    i.user_id,
    btrim(i.category) as display_name,
    lower(btrim(i.category)) as normalized_name,
    row_number() over (
      partition by i.user_id, lower(btrim(i.category))
      order by i.id
    ) as category_rank
  from public.inventory i
  where i.user_id is not null
    and exists (
      select 1
      from auth.users u
      where u.id = i.user_id
    )
    and nullif(btrim(i.category), '') is not null
)
insert into public.categories (user_id, name)
select user_id, display_name
from ranked_legacy_categories
where category_rank = 1
on conflict (user_id, lower(btrim(name))) do nothing;

update public.inventory i
set category_id = c.id,
    category = c.name
from public.categories c
where i.category_id is null
  and i.user_id = c.user_id
  and i.user_id is not null
  and exists (
    select 1
    from auth.users u
    where u.id = i.user_id
  )
  and nullif(btrim(i.category), '') is not null
  and lower(btrim(i.category)) = lower(btrim(c.name));

alter table public.categories enable row level security;

drop policy if exists "Users can view own categories" on public.categories;
create policy "Users can view own categories"
on public.categories
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "Users can create own categories" on public.categories;
create policy "Users can create own categories"
on public.categories
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "Users can update own categories" on public.categories;
create policy "Users can update own categories"
on public.categories
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "Users can delete own categories" on public.categories;
create policy "Users can delete own categories"
on public.categories
for delete
to authenticated
using (auth.uid() = user_id);

revoke all on table public.categories from anon;
revoke all on sequence public.categories_id_seq from anon;

grant select, insert, update, delete on table public.categories to authenticated;
grant usage, select on sequence public.categories_id_seq to authenticated;

notify pgrst, 'reload schema';

commit;
