-- SydIN Phase 8: Purchase Orders (persisted history, expenses, receive-to-stock)
-- Run manually in the Supabase SQL editor after reviewing.
--
-- Follows the conventions of phase-7-pick-lists.sql:
--   * per-user rows guarded by RLS,
--   * stock only changes through stock_movements,
--   * terminal statuses locked down, receive flow gated behind an RPC.

begin;

create table if not exists public.purchase_orders (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  po_number text not null,
  title text null,
  supplier_id bigint null references public.suppliers(id) on delete set null,
  supplier_name_snapshot text null,
  supplier_contact_snapshot text null,
  depot_id bigint null references public.depots(id) on delete set null,
  depot_name_snapshot text null,
  purchase_date date null,
  expected_delivery_date date null,
  status text not null default 'draft',
  payment_method text null,
  paid_by text null,
  payment_status text not null default 'unpaid',
  amount_paid numeric(12, 2) null,
  currency_code text null,
  notes text null,
  internal_reference text null,
  attachment_url text null,
  attachment_label text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  received_at timestamptz null,
  cancelled_at timestamptz null,
  constraint purchase_orders_po_number_not_blank check (btrim(po_number) <> ''),
  constraint purchase_orders_status_valid check (
    status in ('draft', 'ordered', 'received', 'cancelled')
  ),
  constraint purchase_orders_payment_method_valid check (
    payment_method is null
    or payment_method in ('cash', 'card', 'transfer', 'other')
  ),
  constraint purchase_orders_payment_status_valid check (
    payment_status in ('unpaid', 'partial', 'paid')
  ),
  constraint purchase_orders_amount_paid_valid check (
    amount_paid is null or amount_paid >= 0
  ),
  constraint purchase_orders_terminal_state_consistent check (
    (
      status in ('draft', 'ordered')
      and received_at is null
      and cancelled_at is null
    )
    or (status = 'received' and received_at is not null and cancelled_at is null)
    or (status = 'cancelled' and received_at is null and cancelled_at is not null)
  )
);

create table if not exists public.purchase_order_lines (
  id bigint generated by default as identity primary key,
  purchase_order_id bigint not null references public.purchase_orders(id) on delete cascade,
  line_type text not null default 'inventory',
  inventory_item_id bigint null references public.inventory(id) on delete set null,
  affects_stock boolean not null default false,
  expense_category text null,
  name_snapshot text not null,
  sku_snapshot text null,
  item_code_snapshot text null,
  unit_label_snapshot text null,
  quantity numeric(12, 2) not null default 1,
  unit_cost numeric(12, 2) null,
  notes text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint purchase_order_lines_type_valid check (
    line_type in ('inventory', 'expense')
  ),
  constraint purchase_order_lines_expense_category_valid check (
    expense_category is null
    or expense_category in (
      'equipment', 'maintenance', 'supplies', 'services', 'utilities', 'other'
    )
  ),
  constraint purchase_order_lines_quantity_positive check (quantity > 0),
  constraint purchase_order_lines_unit_cost_valid check (
    unit_cost is null or unit_cost >= 0
  ),
  constraint purchase_order_lines_name_not_blank check (
    btrim(name_snapshot) <> ''
  ),
  -- Expense lines never touch stock; inventory links belong to inventory lines only.
  constraint purchase_order_lines_expense_never_stock check (
    line_type <> 'expense' or (affects_stock = false and inventory_item_id is null)
  ),
  constraint purchase_order_lines_stock_needs_item check (
    affects_stock = false or inventory_item_id is not null
  )
);

create index if not exists purchase_orders_user_status_created_idx
  on public.purchase_orders(user_id, status, created_at desc);

create index if not exists purchase_orders_user_purchase_date_idx
  on public.purchase_orders(user_id, purchase_date desc);

create index if not exists purchase_orders_user_depot_idx
  on public.purchase_orders(user_id, depot_id);

create index if not exists purchase_order_lines_order_id_idx
  on public.purchase_order_lines(purchase_order_id);

create index if not exists purchase_order_lines_inventory_item_id_idx
  on public.purchase_order_lines(inventory_item_id);

alter table public.stock_movements
  add column if not exists purchase_order_id bigint null;

alter table public.stock_movements
  add column if not exists purchase_order_line_id bigint null;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'stock_movements_purchase_order_id_fkey'
      and conrelid = 'public.stock_movements'::regclass
  ) then
    alter table public.stock_movements
      add constraint stock_movements_purchase_order_id_fkey
      foreign key (purchase_order_id)
      references public.purchase_orders(id)
      on delete set null;
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'stock_movements_purchase_order_line_id_fkey'
      and conrelid = 'public.stock_movements'::regclass
  ) then
    alter table public.stock_movements
      add constraint stock_movements_purchase_order_line_id_fkey
      foreign key (purchase_order_line_id)
      references public.purchase_order_lines(id)
      on delete set null;
  end if;
end
$$;

create index if not exists stock_movements_purchase_order_id_idx
  on public.stock_movements(purchase_order_id);

create unique index if not exists stock_movements_purchase_order_line_uidx
  on public.stock_movements(purchase_order_line_id)
  where purchase_order_line_id is not null;

create or replace function public.normalize_purchase_order()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.po_number = btrim(new.po_number);
  new.title = nullif(btrim(coalesce(new.title, '')), '');
  new.supplier_name_snapshot = nullif(btrim(coalesce(new.supplier_name_snapshot, '')), '');
  new.supplier_contact_snapshot = nullif(btrim(coalesce(new.supplier_contact_snapshot, '')), '');
  new.depot_name_snapshot = nullif(btrim(coalesce(new.depot_name_snapshot, '')), '');
  new.paid_by = nullif(btrim(coalesce(new.paid_by, '')), '');
  new.notes = nullif(btrim(coalesce(new.notes, '')), '');
  new.internal_reference = nullif(btrim(coalesce(new.internal_reference, '')), '');
  new.attachment_label = nullif(btrim(coalesce(new.attachment_label, '')), '');

  if auth.uid() is null or new.user_id <> auth.uid() then
    raise exception 'Purchase order must belong to the authenticated user.'
      using errcode = '42501';
  end if;

  if tg_op = 'INSERT' then
    if new.status not in ('draft', 'ordered') then
      raise exception 'New purchase orders must start as draft or ordered.'
        using errcode = '23514';
    end if;

    new.received_at = null;
    new.cancelled_at = null;
    return new;
  end if;

  if new.user_id is distinct from old.user_id then
    raise exception 'Purchase order ownership cannot be changed.'
      using errcode = '23514';
  end if;

  if old.status in ('received', 'cancelled')
     and new.status is not distinct from old.status then
    -- Allow harmless metadata edits (payment info, notes, attachment) after receipt,
    -- but never a silent status rewrite.
    new.updated_at = now();
    return new;
  end if;

  if old.status = 'received' and new.status <> 'received' then
    raise exception 'Received purchase orders cannot change status.'
      using errcode = '55000';
  end if;

  if old.status = 'cancelled' and new.status <> 'cancelled' then
    raise exception 'Cancelled purchase orders cannot change status.'
      using errcode = '55000';
  end if;

  if new.status = 'received'
     and coalesce(current_setting('sydin.receive_purchase_order', true), '') <> 'on' then
    raise exception 'Purchase orders must be received through receive_purchase_order.'
      using errcode = '42501';
  end if;

  if new.status = 'cancelled' then
    new.cancelled_at = coalesce(new.cancelled_at, now());
    new.received_at = null;
  elsif new.status in ('draft', 'ordered') then
    new.cancelled_at = null;
    new.received_at = null;
  end if;

  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists purchase_orders_normalize on public.purchase_orders;
create trigger purchase_orders_normalize
before insert or update on public.purchase_orders
for each row
execute function public.normalize_purchase_order();

create or replace function public.normalize_and_validate_purchase_order_line()
returns trigger
language plpgsql
set search_path = public
as $$
declare
  owner_id uuid;
  parent_status text;
begin
  new.name_snapshot = btrim(new.name_snapshot);
  new.sku_snapshot = nullif(btrim(coalesce(new.sku_snapshot, '')), '');
  new.item_code_snapshot = nullif(btrim(coalesce(new.item_code_snapshot, '')), '');
  new.unit_label_snapshot = nullif(btrim(coalesce(new.unit_label_snapshot, '')), '');
  new.notes = nullif(btrim(coalesce(new.notes, '')), '');

  select po.user_id, po.status
  into owner_id, parent_status
  from public.purchase_orders po
  where po.id = new.purchase_order_id;

  if owner_id is null then
    raise exception 'Purchase order not found.'
      using errcode = '23503';
  end if;

  if auth.uid() is null or owner_id <> auth.uid() then
    raise exception 'Purchase order line must belong to the authenticated user.'
      using errcode = '42501';
  end if;

  if parent_status not in ('draft', 'ordered') then
    raise exception 'Received or cancelled purchase order lines cannot be changed.'
      using errcode = '55000';
  end if;

  if new.inventory_item_id is not null
     and not exists (
       select 1
       from public.inventory i
       where i.id = new.inventory_item_id
         and i.user_id = owner_id
     ) then
    raise exception 'Inventory item must belong to the purchase order owner.'
      using errcode = '23514';
  end if;

  if tg_op = 'UPDATE' then
    if new.purchase_order_id is distinct from old.purchase_order_id then
      raise exception 'Purchase order lines cannot be moved between orders.'
        using errcode = '23514';
    end if;

    new.updated_at = now();
  end if;

  return new;
end;
$$;

drop trigger if exists purchase_order_lines_normalize_validate
  on public.purchase_order_lines;
create trigger purchase_order_lines_normalize_validate
before insert or update on public.purchase_order_lines
for each row
execute function public.normalize_and_validate_purchase_order_line();

create or replace function public.guard_purchase_order_line_delete()
returns trigger
language plpgsql
set search_path = public
as $$
declare
  owner_id uuid;
  parent_status text;
begin
  if pg_trigger_depth() > 1 then
    return old;
  end if;

  select po.user_id, po.status
  into owner_id, parent_status
  from public.purchase_orders po
  where po.id = old.purchase_order_id;

  if owner_id is null then
    return old;
  end if;

  if auth.uid() is null or owner_id <> auth.uid() then
    raise exception 'Purchase order line must belong to the authenticated user.'
      using errcode = '42501';
  end if;

  if parent_status not in ('draft', 'ordered') then
    raise exception 'Received or cancelled purchase order lines cannot be removed.'
      using errcode = '55000';
  end if;

  return old;
end;
$$;

drop trigger if exists purchase_order_lines_guard_delete
  on public.purchase_order_lines;
create trigger purchase_order_lines_guard_delete
before delete on public.purchase_order_lines
for each row
execute function public.guard_purchase_order_line_delete();

-- Marks a purchase order as received. Every line with affects_stock adds its
-- quantity to the linked inventory item through a stock_in movement, so the
-- item history shows "Purchase order #N" automatically.
create or replace function public.receive_purchase_order(
  p_purchase_order_id bigint
)
returns public.purchase_orders
language plpgsql
security definer
set search_path = public
as $$
declare
  authenticated_user_id uuid;
  target_order public.purchase_orders%rowtype;
  line_record record;
  quantity_before integer;
  quantity_to_add integer;
begin
  authenticated_user_id := auth.uid();

  if authenticated_user_id is null then
    raise exception 'Authentication is required.'
      using errcode = '42501';
  end if;

  select *
  into target_order
  from public.purchase_orders
  where id = p_purchase_order_id
  for update;

  if not found or target_order.user_id <> authenticated_user_id then
    raise exception 'Purchase order not found.'
      using errcode = '42501';
  end if;

  if target_order.status not in ('draft', 'ordered') then
    raise exception 'Only draft or ordered purchase orders can be received.'
      using errcode = '55000';
  end if;

  perform pol.id
  from public.purchase_order_lines pol
  where pol.purchase_order_id = p_purchase_order_id
  order by pol.id
  for update;

  if not exists (
    select 1
    from public.purchase_order_lines
    where purchase_order_id = p_purchase_order_id
  ) then
    raise exception 'Add at least one line before receiving this purchase order.'
      using errcode = '23514';
  end if;

  if exists (
    select 1
    from public.purchase_order_lines
    where purchase_order_id = p_purchase_order_id
      and affects_stock
      and inventory_item_id is null
  ) then
    raise exception
      'A stock-affecting line lost its inventory item. Edit the line before receiving.'
      using errcode = '23514';
  end if;

  perform i.id
  from public.inventory i
  join public.purchase_order_lines pol
    on pol.inventory_item_id = i.id
  where pol.purchase_order_id = p_purchase_order_id
    and pol.affects_stock
  order by i.id
  for update of i;

  for line_record in
    select
      pol.id as line_id,
      pol.inventory_item_id,
      pol.quantity,
      pol.name_snapshot,
      i.user_id as inventory_user_id,
      i.quantity as inventory_quantity
    from public.purchase_order_lines pol
    join public.inventory i on i.id = pol.inventory_item_id
    where pol.purchase_order_id = p_purchase_order_id
      and pol.affects_stock
    order by i.id
  loop
    if line_record.inventory_user_id <> authenticated_user_id then
      raise exception 'Inventory item ownership does not match the purchase order.'
        using errcode = '42501';
    end if;

    if exists (
      select 1
      from public.stock_movements sm
      where sm.purchase_order_line_id = line_record.line_id
    ) then
      raise exception 'Stock has already been added for this purchase order line.'
        using errcode = '23505';
    end if;

    quantity_to_add := round(line_record.quantity)::integer;

    if quantity_to_add <= 0 then
      raise exception 'Stock-affecting quantity for % must be a positive whole number.',
        line_record.name_snapshot
        using errcode = '23514';
    end if;

    quantity_before := line_record.inventory_quantity;

    update public.inventory
    set quantity = quantity_before + quantity_to_add
    where id = line_record.inventory_item_id
      and user_id = authenticated_user_id;

    insert into public.stock_movements (
      user_id,
      item_id,
      movement_type,
      quantity_delta,
      quantity_before,
      quantity_after,
      notes,
      purchase_order_id,
      purchase_order_line_id
    )
    values (
      authenticated_user_id,
      line_record.inventory_item_id,
      'stock_in',
      quantity_to_add,
      quantity_before,
      quantity_before + quantity_to_add,
      'Purchase order #' || p_purchase_order_id || ': ' || target_order.po_number,
      p_purchase_order_id,
      line_record.line_id
    );
  end loop;

  perform set_config('sydin.receive_purchase_order', 'on', true);

  update public.purchase_orders
  set
    status = 'received',
    received_at = now(),
    cancelled_at = null
  where id = p_purchase_order_id
  returning * into target_order;

  return target_order;
end;
$$;

alter table public.purchase_orders enable row level security;
alter table public.purchase_order_lines enable row level security;

drop policy if exists "Users can view own purchase orders"
  on public.purchase_orders;
create policy "Users can view own purchase orders"
on public.purchase_orders
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "Users can create own purchase orders"
  on public.purchase_orders;
create policy "Users can create own purchase orders"
on public.purchase_orders
for insert
to authenticated
with check (
  auth.uid() = user_id
  and status in ('draft', 'ordered')
);

drop policy if exists "Users can update own purchase orders"
  on public.purchase_orders;
create policy "Users can update own purchase orders"
on public.purchase_orders
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "Users can delete own active purchase orders"
  on public.purchase_orders;
create policy "Users can delete own active purchase orders"
on public.purchase_orders
for delete
to authenticated
using (
  auth.uid() = user_id
  and status in ('draft', 'ordered', 'cancelled')
);

drop policy if exists "Users can view own purchase order lines"
  on public.purchase_order_lines;
create policy "Users can view own purchase order lines"
on public.purchase_order_lines
for select
to authenticated
using (
  exists (
    select 1
    from public.purchase_orders po
    where po.id = purchase_order_id
      and po.user_id = auth.uid()
  )
);

drop policy if exists "Users can create own active purchase order lines"
  on public.purchase_order_lines;
create policy "Users can create own active purchase order lines"
on public.purchase_order_lines
for insert
to authenticated
with check (
  exists (
    select 1
    from public.purchase_orders po
    where po.id = purchase_order_id
      and po.user_id = auth.uid()
      and po.status in ('draft', 'ordered')
  )
  and (
    inventory_item_id is null
    or exists (
      select 1
      from public.inventory i
      where i.id = inventory_item_id
        and i.user_id = auth.uid()
    )
  )
);

drop policy if exists "Users can update own active purchase order lines"
  on public.purchase_order_lines;
create policy "Users can update own active purchase order lines"
on public.purchase_order_lines
for update
to authenticated
using (
  exists (
    select 1
    from public.purchase_orders po
    where po.id = purchase_order_id
      and po.user_id = auth.uid()
      and po.status in ('draft', 'ordered')
  )
)
with check (
  exists (
    select 1
    from public.purchase_orders po
    where po.id = purchase_order_id
      and po.user_id = auth.uid()
      and po.status in ('draft', 'ordered')
  )
);

drop policy if exists "Users can delete own active purchase order lines"
  on public.purchase_order_lines;
create policy "Users can delete own active purchase order lines"
on public.purchase_order_lines
for delete
to authenticated
using (
  exists (
    select 1
    from public.purchase_orders po
    where po.id = purchase_order_id
      and po.user_id = auth.uid()
      and po.status in ('draft', 'ordered')
  )
);

revoke all on table public.purchase_orders from anon;
revoke all on table public.purchase_order_lines from anon;
revoke all on sequence public.purchase_orders_id_seq from anon;
revoke all on sequence public.purchase_order_lines_id_seq from anon;
revoke all on function public.receive_purchase_order(bigint) from public;
revoke all on function public.receive_purchase_order(bigint) from anon;

grant select, insert, update, delete
  on table public.purchase_orders to authenticated;
grant select, insert, update, delete
  on table public.purchase_order_lines to authenticated;
grant usage, select
  on sequence public.purchase_orders_id_seq to authenticated;
grant usage, select
  on sequence public.purchase_order_lines_id_seq to authenticated;
grant execute
  on function public.receive_purchase_order(bigint) to authenticated;

-- Storage bucket for invoice / proof images attached to purchase orders.
-- Public read (same convention as the existing "products" bucket); uploads are
-- restricted to the owner's folder (first path segment = auth.uid()).
insert into storage.buckets (id, name, public)
values ('po-attachments', 'po-attachments', true)
on conflict (id) do nothing;

drop policy if exists "PO attachments are publicly readable"
  on storage.objects;
create policy "PO attachments are publicly readable"
on storage.objects
for select
to public
using (bucket_id = 'po-attachments');

drop policy if exists "Users can upload own PO attachments"
  on storage.objects;
create policy "Users can upload own PO attachments"
on storage.objects
for insert
to authenticated
with check (
  bucket_id = 'po-attachments'
  and (storage.foldername(name))[1] = auth.uid()::text
);

drop policy if exists "Users can delete own PO attachments"
  on storage.objects;
create policy "Users can delete own PO attachments"
on storage.objects
for delete
to authenticated
using (
  bucket_id = 'po-attachments'
  and (storage.foldername(name))[1] = auth.uid()::text
);

notify pgrst, 'reload schema';

commit;
