-- SydIN Phase 4C: Suppliers / Vendors v1
-- Run manually in the Supabase SQL editor.

begin;

create table if not exists public.suppliers (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  contact_name text null,
  phone text null,
  whatsapp text null,
  email text null,
  address text null,
  notes text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.inventory
  add column if not exists supplier_id bigint null;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'inventory_supplier_id_fkey'
      and conrelid = 'public.inventory'::regclass
  ) then
    alter table public.inventory
      add constraint inventory_supplier_id_fkey
      foreign key (supplier_id)
      references public.suppliers(id)
      on delete set null;
  end if;
end
$$;

create unique index if not exists suppliers_user_name_unique_ci
  on public.suppliers (user_id, lower(btrim(name)));

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'suppliers_name_not_blank'
      and conrelid = 'public.suppliers'::regclass
  ) then
    alter table public.suppliers
      add constraint suppliers_name_not_blank
      check (btrim(name) <> '');
  end if;
end
$$;

create index if not exists suppliers_user_id_idx
  on public.suppliers (user_id);

create index if not exists inventory_user_supplier_id_idx
  on public.inventory (user_id, supplier_id);

create or replace function public.set_suppliers_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists suppliers_set_updated_at on public.suppliers;
create trigger suppliers_set_updated_at
before update on public.suppliers
for each row
execute function public.set_suppliers_updated_at();

create or replace function public.validate_inventory_supplier_owner()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  if new.supplier_id is null then
    return new;
  end if;

  if not exists (
    select 1
    from public.suppliers s
    where s.id = new.supplier_id
      and s.user_id = new.user_id
  ) then
    raise exception 'Supplier must belong to the same user as the inventory item'
      using errcode = '23514';
  end if;

  return new;
end;
$$;

drop trigger if exists inventory_validate_supplier_owner on public.inventory;
create trigger inventory_validate_supplier_owner
before insert or update of supplier_id, user_id on public.inventory
for each row
execute function public.validate_inventory_supplier_owner();

alter table public.suppliers enable row level security;

drop policy if exists "Users can view own suppliers" on public.suppliers;
create policy "Users can view own suppliers"
on public.suppliers
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "Users can create own suppliers" on public.suppliers;
create policy "Users can create own suppliers"
on public.suppliers
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "Users can update own suppliers" on public.suppliers;
create policy "Users can update own suppliers"
on public.suppliers
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "Users can delete own suppliers" on public.suppliers;
create policy "Users can delete own suppliers"
on public.suppliers
for delete
to authenticated
using (auth.uid() = user_id);

revoke all on table public.suppliers from anon;
grant select, insert, update, delete on table public.suppliers to authenticated;
grant usage, select on sequence public.suppliers_id_seq to authenticated;

commit;
