-- SydIN Phase 9: Purchase Order payment timeline (per-payment log)
-- Run manually in the Supabase SQL editor after reviewing.
--
-- Adds a payments log so each payment on a purchase order (deposit, balance on
-- delivery, etc.) is recorded with its own date. The order's amount_paid and
-- payment_status become DERIVED from the sum of its payments vs the line total.
--
-- Order of operations matters: the backfill runs BEFORE the triggers exist, so
-- pre-existing amount_paid values seed the log without tripping the auth check.

begin;

create table if not exists public.purchase_order_payments (
  id bigint generated by default as identity primary key,
  purchase_order_id bigint not null
    references public.purchase_orders(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  amount numeric(12, 2) not null,
  method text null,
  paid_by text null,
  note text null,
  paid_at date not null default current_date,
  created_at timestamptz not null default now(),
  constraint purchase_order_payments_amount_positive check (amount > 0),
  constraint purchase_order_payments_method_valid check (
    method is null or method in ('cash', 'card', 'transfer', 'other')
  )
);

create index if not exists purchase_order_payments_order_idx
  on public.purchase_order_payments(purchase_order_id);

create index if not exists purchase_order_payments_user_idx
  on public.purchase_order_payments(user_id);

-- Seed the log from existing amount_paid values (runs before triggers exist).
insert into public.purchase_order_payments (
  purchase_order_id, user_id, amount, method, paid_by, paid_at
)
select
  po.id,
  po.user_id,
  po.amount_paid,
  po.payment_method,
  po.paid_by,
  coalesce(po.purchase_date, po.created_at::date)
from public.purchase_orders po
where po.amount_paid is not null
  and po.amount_paid > 0
  and not exists (
    select 1
    from public.purchase_order_payments p
    where p.purchase_order_id = po.id
  );

-- Recompute the parent order's amount_paid (sum of payments) and payment_status
-- (derived from the sum vs the line total). SECURITY DEFINER so it can update the
-- parent row; the parent's normalize trigger still enforces auth.uid() ownership.
create or replace function public.recompute_purchase_order_payment(p_order_id bigint)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_paid numeric(12, 2);
  v_total numeric(12, 2);
  v_status text;
  v_owner uuid;
begin
  select user_id into v_owner from public.purchase_orders where id = p_order_id;
  if v_owner is null then
    return;
  end if;

  select coalesce(sum(amount), 0)
  into v_paid
  from public.purchase_order_payments
  where purchase_order_id = p_order_id;

  select coalesce(sum(quantity * coalesce(unit_cost, 0)), 0)
  into v_total
  from public.purchase_order_lines
  where purchase_order_id = p_order_id;

  if v_paid <= 0 then
    v_status := 'unpaid';
  elsif v_total > 0 and v_paid >= v_total then
    v_status := 'paid';
  else
    v_status := 'partial';
  end if;

  update public.purchase_orders
  set amount_paid = v_paid,
      payment_status = v_status
  where id = p_order_id;
end;
$$;

create or replace function public.validate_purchase_order_payment()
returns trigger
language plpgsql
set search_path = public
as $$
declare
  v_owner uuid;
begin
  new.paid_by = nullif(btrim(coalesce(new.paid_by, '')), '');
  new.note = nullif(btrim(coalesce(new.note, '')), '');

  select user_id into v_owner
  from public.purchase_orders
  where id = new.purchase_order_id;

  if v_owner is null then
    raise exception 'Purchase order not found.'
      using errcode = '23503';
  end if;

  if auth.uid() is null or v_owner <> auth.uid() then
    raise exception 'Payment must belong to the authenticated user.'
      using errcode = '42501';
  end if;

  new.user_id = v_owner;
  return new;
end;
$$;

drop trigger if exists purchase_order_payments_validate
  on public.purchase_order_payments;
create trigger purchase_order_payments_validate
before insert or update on public.purchase_order_payments
for each row
execute function public.validate_purchase_order_payment();

create or replace function public.on_purchase_order_payment_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'DELETE' then
    perform public.recompute_purchase_order_payment(old.purchase_order_id);
    return old;
  end if;

  perform public.recompute_purchase_order_payment(new.purchase_order_id);
  return new;
end;
$$;

drop trigger if exists purchase_order_payments_recompute
  on public.purchase_order_payments;
create trigger purchase_order_payments_recompute
after insert or update or delete on public.purchase_order_payments
for each row
execute function public.on_purchase_order_payment_change();

alter table public.purchase_order_payments enable row level security;

drop policy if exists "Users can view own PO payments"
  on public.purchase_order_payments;
create policy "Users can view own PO payments"
on public.purchase_order_payments
for select
to authenticated
using (
  exists (
    select 1
    from public.purchase_orders po
    where po.id = purchase_order_id
      and po.user_id = auth.uid()
  )
);

drop policy if exists "Users can add own PO payments"
  on public.purchase_order_payments;
create policy "Users can add own PO payments"
on public.purchase_order_payments
for insert
to authenticated
with check (
  exists (
    select 1
    from public.purchase_orders po
    where po.id = purchase_order_id
      and po.user_id = auth.uid()
  )
);

drop policy if exists "Users can delete own PO payments"
  on public.purchase_order_payments;
create policy "Users can delete own PO payments"
on public.purchase_order_payments
for delete
to authenticated
using (
  exists (
    select 1
    from public.purchase_orders po
    where po.id = purchase_order_id
      and po.user_id = auth.uid()
  )
);

revoke all on table public.purchase_order_payments from anon;
revoke all on sequence public.purchase_order_payments_id_seq from anon;

grant select, insert, delete
  on table public.purchase_order_payments to authenticated;
grant usage, select
  on sequence public.purchase_order_payments_id_seq to authenticated;

-- Reconcile amount_paid / payment_status for every order now that the log exists.
-- normalize_purchase_order() blocks updates to purchase_orders when auth.uid() is
-- null (as it is in the SQL editor), so disable it just for this migration-time
-- recompute, then re-enable it. Runtime is unaffected: when a payment is recorded
-- in the app, auth.uid() is set and the ownership check passes normally.
alter table public.purchase_orders disable trigger purchase_orders_normalize;

do $$
declare
  r record;
begin
  for r in select id from public.purchase_orders loop
    perform public.recompute_purchase_order_payment(r.id);
  end loop;
end
$$;

alter table public.purchase_orders enable trigger purchase_orders_normalize;

notify pgrst, 'reload schema';

commit;
