-- SydIN Phase 20: Sales orders / invoices
--
-- Step 2 of the sales module. A deliberate mirror of phase-8-purchase-orders:
-- an order, its lines, snapshots of everything printed on it, and a status that
-- moves in one direction. The buy side has been in production for months, so the
-- sell side copies its shape rather than inventing a second way to hold a
-- document.
--
-- WHY SNAPSHOTS. `customer_name_snapshot`, `name_snapshot`, `unit_label_snapshot`
-- and the rest exist because an invoice is a record of what was sold on a day,
-- not a live view of the catalogue. Rename a product next month, or change its
-- price, and last month's invoice must still say what the customer actually
-- agreed to. Purchase orders learned this already; sales inherit it.
--
-- WHAT IS NOT HERE YET. No payments table -- that is step 4, and it will mirror
-- phase-9 exactly. `amount_paid` and `payment_status` exist as columns now so
-- the invoice screen has somewhere to read from, and they become DERIVED from
-- the payment log when that arrives, the same way purchase orders did it.
--
-- Run manually in the Supabase SQL editor after reviewing, then read the tables
-- back. Phases 15 and 17 both reported success while changing nothing.

begin;

create table if not exists public.sales_orders (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  invoice_number text not null,
  title text null,
  customer_id bigint null references public.customers(id) on delete set null,
  customer_name_snapshot text null,
  customer_contact_snapshot text null,
  depot_id bigint null references public.depots(id) on delete set null,
  depot_name_snapshot text null,
  issue_date date null,
  due_date date null,
  status text not null default 'draft',
  payment_status text not null default 'unpaid',
  amount_paid numeric(12, 2) null,
  currency_code text null,
  notes text null,
  internal_reference text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  issued_at timestamptz null,
  cancelled_at timestamptz null,
  constraint sales_orders_invoice_number_not_blank
    check (btrim(invoice_number) <> ''),
  -- One direction only: a draft becomes issued, an issued invoice becomes paid,
  -- and anything can be cancelled. There is no route back to draft, because an
  -- issued invoice has already taken stock out and been shown to a customer.
  constraint sales_orders_status_valid check (
    status in ('draft', 'issued', 'paid', 'cancelled')
  ),
  constraint sales_orders_payment_status_valid check (
    payment_status in ('unpaid', 'partial', 'paid')
  ),
  constraint sales_orders_amount_paid_valid check (
    amount_paid is null or amount_paid >= 0
  )
);

-- Invoice numbers are unique per account, not globally: two businesses both
-- starting at INV-0001 is normal and correct.
create unique index if not exists sales_orders_user_invoice_number_unique_ci
  on public.sales_orders (user_id, lower(btrim(invoice_number)));

create index if not exists sales_orders_user_status_created_idx
  on public.sales_orders (user_id, status, created_at desc);

create index if not exists sales_orders_user_issue_date_idx
  on public.sales_orders (user_id, issue_date desc);

create index if not exists sales_orders_user_customer_idx
  on public.sales_orders (user_id, customer_id);

create table if not exists public.sales_order_lines (
  id bigint generated by default as identity primary key,
  sales_order_id bigint not null
    references public.sales_orders(id) on delete cascade,
  line_type text not null default 'inventory',
  inventory_item_id bigint null references public.inventory(id) on delete set null,
  affects_stock boolean not null default false,
  name_snapshot text not null,
  sku_snapshot text null,
  item_code_snapshot text null,
  unit_label_snapshot text null,
  quantity numeric(12, 2) not null default 1,
  unit_price numeric(12, 2) null,
  notes text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  -- A wholesale invoice is mostly products, plus the occasional delivery or
  -- service charge. Same split purchase orders make between inventory and
  -- expense lines.
  constraint sales_order_lines_type_valid check (
    line_type in ('inventory', 'charge')
  ),
  constraint sales_order_lines_quantity_positive check (quantity > 0),
  constraint sales_order_lines_unit_price_valid check (
    unit_price is null or unit_price >= 0
  ),
  constraint sales_order_lines_name_not_blank check (
    btrim(name_snapshot) <> ''
  ),
  -- A charge is not a product, so it can never move stock.
  constraint sales_order_lines_charge_never_stock check (
    line_type <> 'charge' or (affects_stock = false and inventory_item_id is null)
  ),
  -- And nothing can claim to move stock without saying which product.
  constraint sales_order_lines_stock_needs_item check (
    affects_stock = false or inventory_item_id is not null
  )
);

create index if not exists sales_order_lines_order_idx
  on public.sales_order_lines (sales_order_id);

create or replace function public.set_sales_orders_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists sales_orders_set_updated_at on public.sales_orders;
create trigger sales_orders_set_updated_at
before update on public.sales_orders
for each row
execute function public.set_sales_orders_updated_at();

drop trigger if exists sales_order_lines_set_updated_at on public.sales_order_lines;
create trigger sales_order_lines_set_updated_at
before update on public.sales_order_lines
for each row
execute function public.set_sales_orders_updated_at();

-- A line must belong to an order owned by the same account. Without this, the
-- lines table's own policies would be the only guard, and a line could be
-- attached to someone else's invoice by id.
create or replace function public.validate_sales_order_line_owner()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  if not exists (
    select 1
    from public.sales_orders o
    where o.id = new.sales_order_id
      and o.user_id = (select auth.uid())
  ) then
    raise exception 'Sales order line must belong to your own invoice'
      using errcode = '23514';
  end if;

  return new;
end;
$$;

drop trigger if exists sales_order_lines_validate_owner on public.sales_order_lines;
create trigger sales_order_lines_validate_owner
before insert or update of sales_order_id on public.sales_order_lines
for each row
execute function public.validate_sales_order_line_owner();

alter table public.sales_orders enable row level security;
alter table public.sales_order_lines enable row level security;

drop policy if exists "Users can view own sales orders" on public.sales_orders;
create policy "Users can view own sales orders"
on public.sales_orders
for select
to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "Users can create own sales orders" on public.sales_orders;
create policy "Users can create own sales orders"
on public.sales_orders
for insert
to authenticated
with check ((select auth.uid()) = user_id);

drop policy if exists "Users can update own sales orders" on public.sales_orders;
create policy "Users can update own sales orders"
on public.sales_orders
for update
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

drop policy if exists "Users can delete own sales orders" on public.sales_orders;
create policy "Users can delete own sales orders"
on public.sales_orders
for delete
to authenticated
using ((select auth.uid()) = user_id);

-- Line policies reach through to the parent order's owner, so there is exactly
-- one answer to "whose invoice is this".
drop policy if exists "Users can view own sales order lines" on public.sales_order_lines;
create policy "Users can view own sales order lines"
on public.sales_order_lines
for select
to authenticated
using (
  exists (
    select 1 from public.sales_orders o
    where o.id = sales_order_id and o.user_id = (select auth.uid())
  )
);

drop policy if exists "Users can create own sales order lines" on public.sales_order_lines;
create policy "Users can create own sales order lines"
on public.sales_order_lines
for insert
to authenticated
with check (
  exists (
    select 1 from public.sales_orders o
    where o.id = sales_order_id and o.user_id = (select auth.uid())
  )
);

drop policy if exists "Users can update own sales order lines" on public.sales_order_lines;
create policy "Users can update own sales order lines"
on public.sales_order_lines
for update
to authenticated
using (
  exists (
    select 1 from public.sales_orders o
    where o.id = sales_order_id and o.user_id = (select auth.uid())
  )
)
with check (
  exists (
    select 1 from public.sales_orders o
    where o.id = sales_order_id and o.user_id = (select auth.uid())
  )
);

drop policy if exists "Users can delete own sales order lines" on public.sales_order_lines;
create policy "Users can delete own sales order lines"
on public.sales_order_lines
for delete
to authenticated
using (
  exists (
    select 1 from public.sales_orders o
    where o.id = sales_order_id and o.user_id = (select auth.uid())
  )
);

commit;
