-- SydIN Phase 10a: Depot Transfers (Scanner Workspace Stage 2)
-- Run manually in the Supabase SQL editor after reviewing.
--
-- Implements the Transfer mode: whole-item relocation to a different depot
-- with audit trail. Does NOT support partial-quantity transfers.
-- See decision: https://github.com/FlowerSystem-lb/sydin/docs/SYDIN_DECISION_LOG.md

begin;

-- Audit table for depot transfers
create table if not exists public.inventory_depot_transfers (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  inventory_item_id bigint not null references public.inventory(id) on delete restrict,
  from_depot_id bigint null references public.depots(id) on delete set null,
  to_depot_id bigint not null references public.depots(id) on delete restrict,
  moved_by text null,
  notes text null,
  created_at timestamptz not null default now(),
  constraint inventory_depot_transfers_depot_change check (
    from_depot_id is null or from_depot_id <> to_depot_id
  ),
  constraint inventory_depot_transfers_notes_not_blank check (
    notes is null or btrim(notes) <> ''
  )
);

-- Indexes for common queries
create index if not exists inventory_depot_transfers_user_idx
  on public.inventory_depot_transfers(user_id, created_at desc);

create index if not exists inventory_depot_transfers_item_idx
  on public.inventory_depot_transfers(inventory_item_id);

create index if not exists inventory_depot_transfers_from_depot_idx
  on public.inventory_depot_transfers(from_depot_id);

create index if not exists inventory_depot_transfers_to_depot_idx
  on public.inventory_depot_transfers(to_depot_id);

-- RLS: Users can only see/modify transfers for their own inventory items
alter table public.inventory_depot_transfers enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'inventory_depot_transfers'
      and policyname = 'inventory_depot_transfers_user_isolation'
  ) then
    create policy inventory_depot_transfers_user_isolation
      on public.inventory_depot_transfers
      for all
      using (auth.uid() = user_id)
      with check (auth.uid() = user_id);
  end if;
end $$;

-- RPC to perform a depot transfer
-- This is the single writer; the Scanner Workspace calls this, never a direct INSERT
create or replace function public.transfer_inventory_item_to_depot(
  item_id bigint,
  new_depot_id bigint,
  moved_by_name text default null,
  transfer_notes text default null
) returns json as $$
declare
  user_id_var uuid;
  old_depot_id bigint;
  item_name text;
  old_depot_name text;
  new_depot_name text;
begin
  user_id_var := auth.uid();
  if user_id_var is null then
    raise exception 'Not authenticated';
  end if;

  -- Fetch item, check ownership and current depot
  select id, depot_id, name into item_id, old_depot_id, item_name
    from public.inventory
    where id = item_id and user_id = user_id_var
    for update;

  if item_id is null then
    raise exception 'Item not found or access denied';
  end if;

  if old_depot_id = new_depot_id then
    raise exception 'Item is already in the target depot';
  end if;

  -- Fetch depot names for the audit record
  select name into old_depot_name from public.depots where id = old_depot_id;
  select name into new_depot_name from public.depots where id = new_depot_id;

  -- Record the transfer in the audit table
  insert into public.inventory_depot_transfers (
    user_id, inventory_item_id, from_depot_id, to_depot_id, moved_by, notes
  ) values (
    user_id_var,
    item_id,
    old_depot_id,
    new_depot_id,
    coalesce(btrim(moved_by_name), null),
    coalesce(btrim(transfer_notes), null)
  );

  -- Update the item's depot
  update public.inventory
    set depot_id = new_depot_id, updated_at = now()
    where id = item_id;

  -- Return success with details
  return json_build_object(
    'success', true,
    'item_name', item_name,
    'from_depot', old_depot_name,
    'to_depot', new_depot_name,
    'moved_by', coalesce(btrim(moved_by_name), 'Unknown'),
    'notes', transfer_notes
  );
end;
$$ language plpgsql security definer;

grant execute on function public.transfer_inventory_item_to_depot(bigint, bigint, text, text)
  to authenticated;

commit;
