-- SydIN Phase 23: Partial receiving against a purchase order
--
-- Before this, a purchase order was received in one go: "Mark received" added
-- every stock line to inventory and closed the order. Suppliers do not ship
-- like that. 100 cartons are ordered, 60 arrive on Tuesday and 40 the week
-- after -- and the owner needs the system to say "60 received, 40 still to
-- come" in between, not "received" or "not received".
--
-- WHAT CHANGES
--   * purchase_orders gains a status: partially_received.
--   * purchase_order_lines gains received_quantity (kept in step by the RPC).
--   * purchase_order_receipts / _lines: one row per delivery, one per line on
--     it. This is the goods-received history: what arrived, when, how much.
--   * stock_movements gains purchase_order_receipt_id so each stock_in points
--     at the delivery that caused it.
--   * receive_purchase_order_lines(...) receives chosen quantities. The old
--     receive_purchase_order(id) still exists and now means "receive
--     everything still outstanding", so nothing that calls it breaks.
--
-- WHAT DOES NOT CHANGE
--   * Stock still only moves through stock_movements.
--   * Received and cancelled orders stay locked. A partially received order
--     cannot be cancelled -- stock has already been added -- it is either
--     received the rest of the way or closed short (p_close => true), which
--     records the shortfall on the order and marks it received.
--
-- Run manually in the Supabase SQL editor after reviewing. Safe to re-run.

begin;

-- ---------------------------------------------------------------------------
-- 1. Status
-- ---------------------------------------------------------------------------
alter table public.purchase_orders
  drop constraint if exists purchase_orders_status_valid;
alter table public.purchase_orders
  add constraint purchase_orders_status_valid check (
    status in ('draft', 'ordered', 'partially_received', 'received', 'cancelled')
  );

alter table public.purchase_orders
  drop constraint if exists purchase_orders_terminal_state_consistent;
alter table public.purchase_orders
  add constraint purchase_orders_terminal_state_consistent check (
    (
      status in ('draft', 'ordered', 'partially_received')
      and received_at is null
      and cancelled_at is null
    )
    or (status = 'received' and received_at is not null and cancelled_at is null)
    or (status = 'cancelled' and received_at is null and cancelled_at is not null)
  );

-- Set when an order is closed with quantities still outstanding, so the
-- record says "closed short" rather than pretending everything arrived.
alter table public.purchase_orders
  add column if not exists closed_short boolean not null default false;

-- ---------------------------------------------------------------------------
-- 2. Received quantity per line
-- ---------------------------------------------------------------------------
alter table public.purchase_order_lines
  add column if not exists received_quantity numeric(12, 2) not null default 0;

alter table public.purchase_order_lines
  drop constraint if exists purchase_order_lines_received_within_ordered;
alter table public.purchase_order_lines
  add constraint purchase_order_lines_received_within_ordered check (
    received_quantity >= 0 and received_quantity <= quantity
  );

-- Orders received before this migration: every line counts as fully received.
-- The line trigger refuses writes without auth.uid() (null in the SQL editor)
-- and, after this migration, refuses received_quantity edits outside the RPC,
-- so it is switched off for this one statement -- the phase-9 pattern.
alter table public.purchase_order_lines
  disable trigger purchase_order_lines_normalize_validate;

update public.purchase_order_lines pol
set received_quantity = pol.quantity
from public.purchase_orders po
where po.id = pol.purchase_order_id
  and po.status = 'received'
  and pol.received_quantity <> pol.quantity;

alter table public.purchase_order_lines
  enable trigger purchase_order_lines_normalize_validate;

-- One stock movement per line was the rule when a line could only be
-- received once. A line received over two deliveries has two.
drop index if exists public.stock_movements_purchase_order_line_uidx;
create index if not exists stock_movements_purchase_order_line_idx
  on public.stock_movements(purchase_order_line_id)
  where purchase_order_line_id is not null;

-- ---------------------------------------------------------------------------
-- 3. Receipts: one per delivery
-- ---------------------------------------------------------------------------
create table if not exists public.purchase_order_receipts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  purchase_order_id bigint not null references public.purchase_orders(id) on delete cascade,
  receipt_number text not null,
  received_at timestamptz not null default now(),
  notes text null,
  created_at timestamptz not null default now(),
  constraint purchase_order_receipts_number_not_blank check (btrim(receipt_number) <> '')
);

create table if not exists public.purchase_order_receipt_lines (
  id bigint generated by default as identity primary key,
  receipt_id bigint not null references public.purchase_order_receipts(id) on delete cascade,
  purchase_order_line_id bigint not null references public.purchase_order_lines(id) on delete cascade,
  inventory_item_id bigint null references public.inventory(id) on delete set null,
  quantity numeric(12, 2) not null,
  stock_movement_id bigint null references public.stock_movements(id) on delete set null,
  constraint purchase_order_receipt_lines_quantity_positive check (quantity > 0)
);

create index if not exists purchase_order_receipts_order_idx
  on public.purchase_order_receipts(purchase_order_id, received_at desc);
create index if not exists purchase_order_receipts_user_idx
  on public.purchase_order_receipts(user_id, received_at desc);
create index if not exists purchase_order_receipt_lines_receipt_idx
  on public.purchase_order_receipt_lines(receipt_id);
create index if not exists purchase_order_receipt_lines_line_idx
  on public.purchase_order_receipt_lines(purchase_order_line_id);

alter table public.stock_movements
  add column if not exists purchase_order_receipt_id bigint null;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'stock_movements_purchase_order_receipt_id_fkey'
      and conrelid = 'public.stock_movements'::regclass
  ) then
    alter table public.stock_movements
      add constraint stock_movements_purchase_order_receipt_id_fkey
      foreign key (purchase_order_receipt_id)
      references public.purchase_order_receipts(id) on delete set null;
  end if;
end $$;

create index if not exists stock_movements_purchase_order_receipt_id_idx
  on public.stock_movements(purchase_order_receipt_id);

-- ---------------------------------------------------------------------------
-- 4. Triggers: the new status is only reachable through the RPC, and lines
--    stay frozen once anything has been received -- except for the RPC itself
--    updating received_quantity, which carries the same transaction flag the
--    receive path has always used.
-- ---------------------------------------------------------------------------
create or replace function public.normalize_purchase_order()
returns trigger
language plpgsql
set search_path = public
as $$
declare
  receiving boolean :=
    coalesce(current_setting('sydin.receive_purchase_order', true), '') = 'on';
begin
  new.po_number = btrim(new.po_number);
  new.title = nullif(btrim(coalesce(new.title, '')), '');
  new.supplier_name_snapshot = nullif(btrim(coalesce(new.supplier_name_snapshot, '')), '');
  new.supplier_contact_snapshot = nullif(btrim(coalesce(new.supplier_contact_snapshot, '')), '');
  new.depot_name_snapshot = nullif(btrim(coalesce(new.depot_name_snapshot, '')), '');
  new.paid_by = nullif(btrim(coalesce(new.paid_by, '')), '');
  new.notes = nullif(btrim(coalesce(new.notes, '')), '');
  new.internal_reference = nullif(btrim(coalesce(new.internal_reference, '')), '');
  new.attachment_label = nullif(btrim(coalesce(new.attachment_label, '')), '');

  if auth.uid() is null or new.user_id <> auth.uid() then
    raise exception 'Purchase order must belong to the authenticated user.'
      using errcode = '42501';
  end if;

  if tg_op = 'INSERT' then
    if new.status not in ('draft', 'ordered') then
      raise exception 'New purchase orders must start as draft or ordered.'
        using errcode = '23514';
    end if;
    new.received_at = null;
    new.cancelled_at = null;
    new.closed_short = false;
    return new;
  end if;

  if new.user_id is distinct from old.user_id then
    raise exception 'Purchase order ownership cannot be changed.'
      using errcode = '23514';
  end if;

  -- Same status: metadata edits (payment, notes, attachment) are fine at any
  -- stage, closed_short is only ever set by the RPC.
  if old.status = new.status then
    if new.closed_short is distinct from old.closed_short and not receiving then
      new.closed_short = old.closed_short;
    end if;
    new.updated_at = now();
    return new;
  end if;

  if old.status = 'received' then
    raise exception 'Received purchase orders cannot change status.'
      using errcode = '55000';
  end if;

  if old.status = 'cancelled' then
    raise exception 'Cancelled purchase orders cannot change status.'
      using errcode = '55000';
  end if;

  if old.status = 'partially_received' and new.status <> 'received' then
    raise exception
      'Stock has already been received on this order. Receive the rest, or close it short.'
      using errcode = '55000';
  end if;

  if new.status in ('received', 'partially_received') and not receiving then
    raise exception 'Purchase orders must be received through receive_purchase_order_lines.'
      using errcode = '42501';
  end if;

  if new.status = 'cancelled' then
    new.cancelled_at = coalesce(new.cancelled_at, now());
    new.received_at = null;
  elsif new.status in ('draft', 'ordered', 'partially_received') then
    new.cancelled_at = null;
    new.received_at = null;
  end if;

  new.updated_at = now();
  return new;
end;
$$;

create or replace function public.normalize_and_validate_purchase_order_line()
returns trigger
language plpgsql
set search_path = public
as $$
declare
  owner_id uuid;
  parent_status text;
  receiving boolean :=
    coalesce(current_setting('sydin.receive_purchase_order', true), '') = 'on';
begin
  new.name_snapshot = btrim(new.name_snapshot);
  new.sku_snapshot = nullif(btrim(coalesce(new.sku_snapshot, '')), '');
  new.item_code_snapshot = nullif(btrim(coalesce(new.item_code_snapshot, '')), '');
  new.unit_label_snapshot = nullif(btrim(coalesce(new.unit_label_snapshot, '')), '');
  new.notes = nullif(btrim(coalesce(new.notes, '')), '');

  select po.user_id, po.status
  into owner_id, parent_status
  from public.purchase_orders po
  where po.id = new.purchase_order_id;

  if owner_id is null then
    raise exception 'Purchase order not found.'
      using errcode = '23503';
  end if;

  if auth.uid() is null or owner_id <> auth.uid() then
    raise exception 'Purchase order line must belong to the authenticated user.'
      using errcode = '42501';
  end if;

  -- The receive RPC is the only writer allowed on a frozen order, and the only
  -- thing it changes is received_quantity.
  if tg_op = 'UPDATE' and receiving then
    if new.quantity is distinct from old.quantity
       or new.inventory_item_id is distinct from old.inventory_item_id
       or new.affects_stock is distinct from old.affects_stock
       or new.purchase_order_id is distinct from old.purchase_order_id then
      raise exception 'Receiving may only change the received quantity.'
        using errcode = '23514';
    end if;
    new.updated_at = now();
    return new;
  end if;

  if parent_status not in ('draft', 'ordered') then
    raise exception 'Lines cannot change once an order has been received or cancelled.'
      using errcode = '55000';
  end if;

  if tg_op = 'INSERT' then
    new.received_quantity = 0;
  elsif new.received_quantity is distinct from old.received_quantity then
    raise exception 'Received quantity is set by receiving, not by editing the line.'
      using errcode = '23514';
  end if;

  if new.inventory_item_id is not null
     and not exists (
       select 1
       from public.inventory i
       where i.id = new.inventory_item_id
         and i.user_id = owner_id
     ) then
    raise exception 'Inventory item must belong to the purchase order owner.'
      using errcode = '23514';
  end if;

  if tg_op = 'UPDATE' then
    if new.purchase_order_id is distinct from old.purchase_order_id then
      raise exception 'Purchase order lines cannot be moved between orders.'
        using errcode = '23514';
    end if;
    new.updated_at = now();
  end if;

  return new;
end;
$$;

-- ---------------------------------------------------------------------------
-- 5. The receive RPC
--
--    p_lines: [{"line_id": 12, "quantity": 60}, ...]
--             Only lines with quantity > 0 are received. Expense lines may be
--             listed (they count toward "everything arrived") but never touch
--             stock.
--    p_close: true closes the order as received even if some quantity is
--             still outstanding (supplier will not ship the rest).
-- ---------------------------------------------------------------------------
create or replace function public.receive_purchase_order_lines(
  p_purchase_order_id bigint,
  p_lines jsonb,
  p_notes text default null,
  p_close boolean default false
)
returns public.purchase_orders
language plpgsql
security definer
set search_path = public
as $$
declare
  authenticated_user_id uuid;
  target_order public.purchase_orders%rowtype;
  entry jsonb;
  line_row public.purchase_order_lines%rowtype;
  requested numeric(12, 2);
  whole_quantity integer;
  quantity_before integer;
  inventory_owner uuid;
  receipt_id bigint;
  receipt_seq integer;
  received_anything boolean := false;
  outstanding numeric(12, 2);
  movement_id bigint;
begin
  authenticated_user_id := auth.uid();

  if authenticated_user_id is null then
    raise exception 'Authentication is required.'
      using errcode = '42501';
  end if;

  if p_lines is null or jsonb_typeof(p_lines) <> 'array' then
    raise exception 'Lines to receive must be a list.'
      using errcode = '22023';
  end if;

  select *
  into target_order
  from public.purchase_orders
  where id = p_purchase_order_id
  for update;

  if not found or target_order.user_id <> authenticated_user_id then
    raise exception 'Purchase order not found.'
      using errcode = '42501';
  end if;

  if target_order.status not in ('draft', 'ordered', 'partially_received') then
    raise exception 'Only open purchase orders can be received.'
      using errcode = '55000';
  end if;

  if not exists (
    select 1 from public.purchase_order_lines
    where purchase_order_id = p_purchase_order_id
  ) then
    raise exception 'Add at least one line before receiving this purchase order.'
      using errcode = '23514';
  end if;

  perform set_config('sydin.receive_purchase_order', 'on', true);

  -- Receipt number: PO-2026-001 -> PO-2026-001/R1, /R2 ...
  select count(*) + 1
  into receipt_seq
  from public.purchase_order_receipts
  where purchase_order_id = p_purchase_order_id;

  insert into public.purchase_order_receipts (
    user_id, purchase_order_id, receipt_number, notes
  )
  values (
    authenticated_user_id,
    p_purchase_order_id,
    target_order.po_number || '/R' || receipt_seq,
    nullif(btrim(coalesce(p_notes, '')), '')
  )
  returning id into receipt_id;

  for entry in select * from jsonb_array_elements(p_lines)
  loop
    requested := coalesce((entry ->> 'quantity')::numeric, 0);
    if requested <= 0 then
      continue;
    end if;

    select *
    into line_row
    from public.purchase_order_lines
    where id = (entry ->> 'line_id')::bigint
      and purchase_order_id = p_purchase_order_id
    for update;

    if not found then
      raise exception 'Line % does not belong to this purchase order.',
        entry ->> 'line_id'
        using errcode = '23503';
    end if;

    if line_row.received_quantity + requested > line_row.quantity then
      raise exception
        'Cannot receive % of "%": only % still outstanding.',
        requested, line_row.name_snapshot,
        line_row.quantity - line_row.received_quantity
        using errcode = '23514';
    end if;

    movement_id := null;

    if line_row.affects_stock then
      if line_row.inventory_item_id is null then
        raise exception
          'The item for "%" was deleted. Edit the order before receiving it.',
          line_row.name_snapshot
          using errcode = '23514';
      end if;

      whole_quantity := round(requested)::integer;
      if whole_quantity <= 0 or whole_quantity <> requested then
        raise exception
          'Stock quantity for "%" must be a positive whole number.',
          line_row.name_snapshot
          using errcode = '23514';
      end if;

      select i.user_id, i.quantity
      into inventory_owner, quantity_before
      from public.inventory i
      where i.id = line_row.inventory_item_id
      for update;

      if inventory_owner is null or inventory_owner <> authenticated_user_id then
        raise exception 'Inventory item ownership does not match the purchase order.'
          using errcode = '42501';
      end if;

      update public.inventory
      set quantity = quantity_before + whole_quantity
      where id = line_row.inventory_item_id;

      insert into public.stock_movements (
        user_id, item_id, movement_type, quantity_delta,
        quantity_before, quantity_after, notes,
        purchase_order_id, purchase_order_line_id, purchase_order_receipt_id
      )
      values (
        authenticated_user_id,
        line_row.inventory_item_id,
        'stock_in',
        whole_quantity,
        quantity_before,
        quantity_before + whole_quantity,
        'Purchase order #' || p_purchase_order_id || ': ' || target_order.po_number
          || ' (' || target_order.po_number || '/R' || receipt_seq || ')',
        p_purchase_order_id,
        line_row.id,
        receipt_id
      )
      returning id into movement_id;
    end if;

    insert into public.purchase_order_receipt_lines (
      receipt_id, purchase_order_line_id, inventory_item_id, quantity, stock_movement_id
    )
    values (
      receipt_id, line_row.id, line_row.inventory_item_id, requested, movement_id
    );

    update public.purchase_order_lines
    set received_quantity = received_quantity + requested
    where id = line_row.id;

    received_anything := true;
  end loop;

  if not received_anything then
    if not p_close then
      raise exception 'Enter a quantity for at least one line.'
        using errcode = '23514';
    end if;
    -- Closing short with nothing new: no delivery happened, so no receipt row.
    delete from public.purchase_order_receipts where id = receipt_id;
  end if;

  select coalesce(sum(quantity - received_quantity), 0)
  into outstanding
  from public.purchase_order_lines
  where purchase_order_id = p_purchase_order_id;

  if outstanding <= 0 or p_close then
    update public.purchase_orders
    set
      status = 'received',
      received_at = now(),
      cancelled_at = null,
      closed_short = (outstanding > 0)
    where id = p_purchase_order_id
    returning * into target_order;
  else
    update public.purchase_orders
    set
      status = 'partially_received',
      received_at = null,
      cancelled_at = null
    where id = p_purchase_order_id
    returning * into target_order;
  end if;

  return target_order;
end;
$$;

-- The one-shot receive keeps its name and meaning for every caller: receive
-- everything still outstanding.
create or replace function public.receive_purchase_order(
  p_purchase_order_id bigint
)
returns public.purchase_orders
language plpgsql
security definer
set search_path = public
as $$
declare
  remaining jsonb;
begin
  select coalesce(
    jsonb_agg(jsonb_build_object('line_id', id, 'quantity', quantity - received_quantity)),
    '[]'::jsonb
  )
  into remaining
  from public.purchase_order_lines
  where purchase_order_id = p_purchase_order_id
    and quantity > received_quantity;

  return public.receive_purchase_order_lines(p_purchase_order_id, remaining, null, true);
end;
$$;

-- ---------------------------------------------------------------------------
-- 6. Row security: receipts are read by their owner and written only by the
--    RPC (security definer), so no insert/update/delete policies.
-- ---------------------------------------------------------------------------
alter table public.purchase_order_receipts enable row level security;
alter table public.purchase_order_receipt_lines enable row level security;

drop policy if exists "Users can view own purchase order receipts"
  on public.purchase_order_receipts;
create policy "Users can view own purchase order receipts"
on public.purchase_order_receipts
for select
to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "Users can view own purchase order receipt lines"
  on public.purchase_order_receipt_lines;
create policy "Users can view own purchase order receipt lines"
on public.purchase_order_receipt_lines
for select
to authenticated
using (
  exists (
    select 1
    from public.purchase_order_receipts r
    where r.id = receipt_id
      and r.user_id = (select auth.uid())
  )
);

-- Line update policy: the RPC runs as definer, so the user-facing policy stays
-- draft/ordered only. Nothing to change there.

revoke all on table public.purchase_order_receipts from anon;
revoke all on table public.purchase_order_receipt_lines from anon;
grant select on table public.purchase_order_receipts to authenticated;
grant select on table public.purchase_order_receipt_lines to authenticated;

revoke all on function public.receive_purchase_order_lines(bigint, jsonb, text, boolean) from public;
revoke all on function public.receive_purchase_order_lines(bigint, jsonb, text, boolean) from anon;
grant execute on function public.receive_purchase_order_lines(bigint, jsonb, text, boolean) to authenticated;

revoke all on function public.receive_purchase_order(bigint) from public;
revoke all on function public.receive_purchase_order(bigint) from anon;
grant execute on function public.receive_purchase_order(bigint) to authenticated;

notify pgrst, 'reload schema';

commit;
