-- SydIN Phase 22: Payments against an invoice
--
-- Step 4 of the sales module. A mirror of phase-9-purchase-order-payments: a
-- log with one row per payment, and an order whose amount_paid and
-- payment_status are DERIVED from that log rather than typed.
--
-- WHY A LOG AND NOT A FIELD. A wholesale invoice is rarely settled in one go --
-- a deposit on order, the balance on delivery, sometimes a third payment weeks
-- later. A single "amount paid" field cannot answer "when did they pay the
-- first half", which is the question that gets asked when a customer disputes
-- a balance. Purchase orders learned this; sales inherit it.
--
-- ONE THING THIS DOES THAT THE BUY SIDE DOES NOT. An invoice has a `paid`
-- status of its own, so when the payments cover the total the order moves from
-- issued to paid, and back to issued if a payment is later removed. The buy
-- side keeps status and payment_status entirely separate; here the lifecycle
-- genuinely ends at paid, and leaving an invoice reading "issued" while fully
-- settled would make the Sales list lie about what is outstanding.
--
-- Run manually in the Supabase SQL editor after reviewing, then test it by
-- trying to break it.

begin;

create table if not exists public.sales_order_payments (
  id bigint generated by default as identity primary key,
  sales_order_id bigint not null
    references public.sales_orders(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  amount numeric(12, 2) not null,
  method text null,
  received_by text null,
  note text null,
  paid_at date not null default current_date,
  created_at timestamptz not null default now(),
  constraint sales_order_payments_amount_positive check (amount > 0),
  constraint sales_order_payments_method_valid check (
    method is null or method in ('cash', 'card', 'transfer', 'other')
  )
);

create index if not exists sales_order_payments_order_idx
  on public.sales_order_payments (sales_order_id);

create index if not exists sales_order_payments_user_idx
  on public.sales_order_payments (user_id);

-- Recompute the invoice's amount_paid and payment_status from the log, and move
-- the lifecycle status with it. SECURITY DEFINER so it can write the parent row.
create or replace function public.recompute_sales_order_payment(p_order_id bigint)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_paid numeric(12, 2);
  v_total numeric(12, 2);
  v_status text;
  v_owner uuid;
  v_order_status text;
begin
  select user_id, status into v_owner, v_order_status
  from public.sales_orders where id = p_order_id;

  if v_owner is null then
    return;
  end if;

  select coalesce(sum(amount), 0) into v_paid
  from public.sales_order_payments
  where sales_order_id = p_order_id;

  select coalesce(sum(quantity * coalesce(unit_price, 0)), 0) into v_total
  from public.sales_order_lines
  where sales_order_id = p_order_id;

  if v_paid <= 0 then
    v_status := 'unpaid';
  elsif v_total > 0 and v_paid >= v_total then
    v_status := 'paid';
  else
    v_status := 'partial';
  end if;

  -- The lifecycle follows the money, but only between issued and paid. A draft
  -- stays a draft (nothing has shipped) and a cancelled invoice stays
  -- cancelled -- a payment against a cancelled sale is a refund problem, not a
  -- reason to quietly bring it back to life.
  if v_status = 'paid' and v_order_status = 'issued' then
    v_order_status := 'paid';
  elsif v_status <> 'paid' and v_order_status = 'paid' then
    v_order_status := 'issued';
  end if;

  update public.sales_orders
  set amount_paid = v_paid,
      payment_status = v_status,
      status = v_order_status
  where id = p_order_id;
end;
$$;

create or replace function public.validate_sales_order_payment()
returns trigger
language plpgsql
set search_path = public
as $$
declare
  v_owner uuid;
  v_status text;
begin
  new.received_by = nullif(btrim(coalesce(new.received_by, '')), '');
  new.note = nullif(btrim(coalesce(new.note, '')), '');

  select user_id, status into v_owner, v_status
  from public.sales_orders
  where id = new.sales_order_id;

  if v_owner is null then
    raise exception 'Invoice not found.'
      using errcode = '23503';
  end if;

  if auth.uid() is null or v_owner <> auth.uid() then
    raise exception 'Payment must belong to the authenticated user.'
      using errcode = '42501';
  end if;

  -- Money against a draft would be money against something the customer has
  -- never been shown, and against a cancelled invoice it is a refund, not a
  -- receipt. Both are refused here rather than left to the screen.
  if v_status = 'draft' then
    raise exception 'Issue this invoice before recording a payment.'
      using errcode = '55000';
  end if;

  if v_status = 'cancelled' then
    raise exception 'This invoice was cancelled.'
      using errcode = '55000';
  end if;

  new.user_id = v_owner;
  return new;
end;
$$;

drop trigger if exists sales_order_payments_validate
  on public.sales_order_payments;
create trigger sales_order_payments_validate
before insert or update on public.sales_order_payments
for each row
execute function public.validate_sales_order_payment();

create or replace function public.on_sales_order_payment_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'DELETE' then
    perform public.recompute_sales_order_payment(old.sales_order_id);
    return old;
  end if;

  perform public.recompute_sales_order_payment(new.sales_order_id);
  return new;
end;
$$;

drop trigger if exists sales_order_payments_recompute
  on public.sales_order_payments;
create trigger sales_order_payments_recompute
after insert or update or delete on public.sales_order_payments
for each row
execute function public.on_sales_order_payment_change();

alter table public.sales_order_payments enable row level security;

drop policy if exists "Users can view own invoice payments"
  on public.sales_order_payments;
create policy "Users can view own invoice payments"
on public.sales_order_payments
for select
to authenticated
using (
  exists (
    select 1 from public.sales_orders o
    where o.id = sales_order_id and o.user_id = (select auth.uid())
  )
);

drop policy if exists "Users can add own invoice payments"
  on public.sales_order_payments;
create policy "Users can add own invoice payments"
on public.sales_order_payments
for insert
to authenticated
with check (
  exists (
    select 1 from public.sales_orders o
    where o.id = sales_order_id and o.user_id = (select auth.uid())
  )
);

drop policy if exists "Users can delete own invoice payments"
  on public.sales_order_payments;
create policy "Users can delete own invoice payments"
on public.sales_order_payments
for delete
to authenticated
using (
  exists (
    select 1 from public.sales_orders o
    where o.id = sales_order_id and o.user_id = (select auth.uid())
  )
);

revoke all on function public.recompute_sales_order_payment(bigint) from public;
revoke all on function public.recompute_sales_order_payment(bigint) from anon;

commit;
