-- SydIN Phase 19: Customers (the sell side of Suppliers)
--
-- Step 1 of the sales module. SydIN already knows who it BUYS from; this is who
-- it SELLS to. Deliberately a mirror of phase-4c-suppliers.sql -- same columns,
-- same constraints, same trigger shape -- because that table has been in
-- production for months and every screen, export and RLS habit already assumes
-- its shape.
--
-- Two differences from suppliers, both intentional:
--
--   1. No foreign key onto inventory. A product has a supplier; a product does
--      not have a customer. The link to a customer belongs on a sale, which is
--      phase 20.
--
--   2. Policies use `(select auth.uid())` rather than bare `auth.uid()`.
--      Phase 17 rewrote all 60 existing policies for exactly this reason: the
--      bare call re-evaluates per row, the subselect becomes a one-time
--      InitPlan. New tables start correct rather than needing the same sweep.
--
-- Run manually in the Supabase SQL editor after reviewing, then read the table
-- back. A clean run proves nothing -- phases 15 and 17 both "succeeded" while
-- changing nothing.

begin;

create table if not exists public.customers (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  contact_name text null,
  phone text null,
  whatsapp text null,
  email text null,
  address text null,
  notes text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- One customer per name per account, case- and whitespace-insensitive, so
-- "Ali Trading", "ali trading" and " Ali Trading " cannot become three rows
-- that each hold part of the history.
create unique index if not exists customers_user_name_unique_ci
  on public.customers (user_id, lower(btrim(name)));

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'customers_name_not_blank'
      and conrelid = 'public.customers'::regclass
  ) then
    alter table public.customers
      add constraint customers_name_not_blank
      check (btrim(name) <> '');
  end if;
end
$$;

create index if not exists customers_user_id_idx
  on public.customers (user_id);

create or replace function public.set_customers_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists customers_set_updated_at on public.customers;
create trigger customers_set_updated_at
before update on public.customers
for each row
execute function public.set_customers_updated_at();

alter table public.customers enable row level security;

drop policy if exists "Users can view own customers" on public.customers;
create policy "Users can view own customers"
on public.customers
for select
to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "Users can create own customers" on public.customers;
create policy "Users can create own customers"
on public.customers
for insert
to authenticated
with check ((select auth.uid()) = user_id);

drop policy if exists "Users can update own customers" on public.customers;
create policy "Users can update own customers"
on public.customers
for update
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

drop policy if exists "Users can delete own customers" on public.customers;
create policy "Users can delete own customers"
on public.customers
for delete
to authenticated
using ((select auth.uid()) = user_id);

commit;
